apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-apps-boundlexx
  namespace: flux-system
spec:
  targetNamespace: boundlexx
  interval: 10m0s
  path: ./apps/08-external-apps/01-boundlexx
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
