apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boundlexx-data
  namespace: boundlexx
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
