apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: protonmail-bridge
  namespace: media
spec:
  interval: 12h
  url: oci://tccr.io/truecharts/protonmail-bridge
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  ref:
    semver: "16.*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: core-apps-protonmail-bridge
  namespace: mail
spec:
  releaseName: protonmail-bridge
  targetNamespace: mail
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: protonmail-bridge
  values:
    env:
      TZ: America/New_York
    persistence:
      config:
        enabled: true
        mountPath: /root
        accessMode: ReadWriteOnce
        size: 200Gi
