apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 12h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: disks-csi-driver-smb
  namespace: kube-system
spec:
  releaseName: csi-driver-smb
  targetNamespace: kube-system
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: csi-driver-smb
      version: "v1.*"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
