apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
  namespace: ssh
  labels:
    app.kubernetes.io/name: bastion
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: bastion
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bastion
    spec:
      containers:
      - name: sshd
        image: lscr.io/linuxserver/openssh-server:9.7_p1-r4-ls169 # {"$imagepolicy": "flux-system:ssh-bastion-policy"}
        imagePullPolicy: IfNotPresent
        ports:
        - name: ssh
          containerPort: 2222
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        volumeMounts:
        - name: sshd-config
          mountPath: /config
        - name: sshd-logs
          mountPath: /config/logs
        - name: sshd-startup
          mountPath: /custom-cont-init.d/
        - name: sshd-keys
          mountPath: /etc/keys
        - name: sshd-cbailey
          mountPath: /home/cbailey/work
        livenessProbe:
          tcpSocket:
            port: ssh
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: ssh
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
          limits:
            cpu: "2000m"
            memory: "4000Mi"
      volumes:
      - name: sshd-config
        persistentVolumeClaim:
          claimName: sshd-config
      - name: sshd-logs
        emptyDir: {}
      - name: sshd-cbailey
        persistentVolumeClaim:
          claimName: sshd-cbailey
      - name: sshd-startup
        configMap:
          name: sshd-startup
          items:
          - key: 01-create-users.sh
            path: 01-create-users.sh
      - name: sshd-keys
        configMap:
          name: sshd-keys
          items:
          - key: cbailey
            path: cbailey
          - key: bashrc
            path: bashrc
