apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sshd-config
  namespace: ssh
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sshd-cbailey
  namespace: ssh
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
