apiVersion: v1
kind: Service
metadata:
  name: bastion
  namespace: ssh
  labels:
    app.kubernetes.io/name: bastion
spec:
  selector:
    app.kubernetes.io/name: bastion
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
  type: ClusterIP
