apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflare-tunnel
  namespace: ingress
  labels:
    release: prometheus
    app.kubernetes.to/component: metrics
    app.kubernetes.io/instance: cloudflare-tunnel
    app.kubernetes.io/name: cloudflare-tunnel
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: cloudflare-tunnel
      app.kubernetes.io/name: cloudflare-tunnel
  podMetricsEndpoints:
  - port: metrics
