---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cf-tunnel-secret
  namespace: ingress
spec:
  encryptedData:
    credentials.json: AgCppCGc907a8gLjKT/w+bFstDlFEL/fUDrDqFe4h3/JHHFbUtD+5S/WIa09m58+qwHf+zkq1GixbITx2S6EvIJ+0xw+iOLQ1LiU9EGiXWJSf9KpBu5tDE/P5UOBZO74kTXfl5M3TyP3iI+wh4fn7+Tyi5BsxYk9SZWdWCejTHAXOXOPWrvYz3cRvFFApHaCn8hH1kgG/9YVzNf8Zi00Q5jOqJst4KdVNWL3qRCjkERzsFWTSfK7yIs5jK7b8+VgSrAb+7t7ICmEK2GBD+5Ezl+RRJ9MwzsUm5QPFWUUyRem4yucV+zkSylavhwIizl5QHuCm+N+owahh5E2DKWxFSBF8aLBWC9lcGC3zhNdKhQxjEIOU0deInAhOFV4WdPZJ+BNXnchN/2ljpGZVZGvytqyHOfKs+CqZrlYCItEQdg4OPa575OVUwkfypUy3DVJO0EVudx2nAAbXlm4sDjoG4JN7DNby/6W+6Y0xsjyr1YByk531I0669o8seFWzSEUU2Yf3x8P8NGaHkCo4hBM4E/I3HpdXcMu6drFA+Qjorr3iHqSTld5eIsDMHvBYkBhI7LzCItTfp5WnG8WwCbYi7Id/m4X24e/UXguJkXWyxa0FGrYbGcfN04pwjfbNxf3MWvutxvx3z3W8tWfM/bNwdDWZtUoTkk3FpvPoXVsa3sp+xlYc6LKc+ZL6CTRl0Tkuxxp2N0RP1bVUxMA536ztfXzMpDjc3u6kq8F7g6KfnU6LVHxDxhXYJfhWP+Lt7+CGFKcH6YLaO1MPfSHY2IHk/VIw+ibRiGLOuAXVT4PtlvCw45AGgM/fzt40ENc9szp5LX8+5QxlWy99koHIBd+s/qd6RORf5+lgzCZ+G5L1sFEckTAdonZ7b8R5ex+FHTfUKR/OgTWSp40l+pIrHRPlgZ/9+gWZAF1SctPQy6KZ0YMYjmfauyRtt5Y6z1hqc+jNIVVE0xR8g3TJ1wzcCkxVb9vdcjig1nxw4lEL5uK2juSzjXLodNwh63ATZHsd9M8PzvBmTpp3KnhX7yrG6B9ukL8mDNJhAoIn2yXoIdolbQBi8y1fu7KFOUTvLg7HgV+kD0zwlST77mZiQtUtz/AZOs=
  template:
    metadata:
      creationTimestamp: null
      name: cf-tunnel-secret
      namespace: ingress
    type: Opaque
