apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-data
  namespace: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
