apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 12h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-insecure
  namespace: ingress
spec:
  releaseName: ingress-nginx-insecure
  targetNamespace: ingress
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.*"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  valuesFrom:
    - kind: Secret
      name: maxmind-key
      valuesKey: key
      targetPath: "controller.maxmindLicenseKey"
  values:
    controller:
      config:
        use-http2: true
        hide-headers: server
        enable-ocsp: true
        use-gzip: true
        enable-brotli: true
        use-geoip2: true
        enable-real-ip: true
        use-forwarded-headers: "true"
        forwarded-for-header: "CF-Connecting-IP"
        proxy-real-ip-cidr: "10.0.0.0/8,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,"
      ingressClassResource:
        name: nginx-insecure
        default: true
        controllerValue: k8s.io/ingress-nginx-insecure
      ingressClass: nginx-insecure
      extraArgs:
        default-ssl-certificate: "ingress/cert-wl-mort-is"
      replicaCount: 2
      service:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.3.225
        externalTrafficPolicy: "Local"
      metrics:
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-secure
  namespace: ingress
spec:
  releaseName: ingress-nginx-secure
  targetNamespace: ingress
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.*"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  valuesFrom:
    - kind: Secret
      name: maxmind-key
      valuesKey: key
      targetPath: "controller.maxmindLicenseKey"
  values:
    controller:
      config:
        use-http2: true
        hide-headers: server
        enable-ocsp: true
        use-gzip: true
        enable-brotli: true
        use-geoip2: true
        enable-real-ip: true
        use-forwarded-headers: "true"
        forwarded-for-header: "CF-Connecting-IP"
        proxy-real-ip-cidr: "10.0.0.0/8,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,"
      allowSnippetAnnotations: true
      ingressClassResource:
        name: nginx-secure
        default: false
        controllerValue: k8s.io/ingress-nginx-secure
      ingressClass: nginx-secure
      extraArgs:
        default-ssl-certificate: "ingress/cert-wl-mort-is"
      replicaCount: 2
      service:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.2.225
        externalTrafficPolicy: "Local"
      metrics:
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus
