apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: plex
  namespace: media
spec:
  interval: 12h
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: media-apps-plex
  namespace: media
spec:
  releaseName: plex
  targetNamespace: media
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: plex
      version: "1.*"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: plex
  values:
    pms:
      storageClassName: longhorn
      configStorage: 500Gi
      resources:
        requests:
          cpu: 4000m
          memory: 3Gi
        limits:
          cpu: 24000m
          memory: 6Gi
    ingress:
      enabled: true
      ingressClassName: nginx-insecure
      url: plex.wl.mort.is
      tls:
        - hosts:
          - plex.wl.mort.is
          secretName: cert-plex-wl-mort-is
      annotations:
        nginx.ingress.kubernetes.io/upstream-vhost: "plex.wl.mort.is"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    service:
      type: LoadBalancer
      port: 32400
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.3.230
    nodeSelector:
      kubernetes.io/hostname: storage-1
