---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: auth
spec:
  encryptedData:
    values.yaml: AgBqph9lta1Re+YQXN4XHnmurhJX/IxXxwDqGXBwOpBXTqVhWa5xXk9hb/h79NzqRuA9i6bzIdktJzYBmDk0jdnZHaKfYyvKYBBRs12QueBNdq5KoYHCBci4CKov0YCsxqJdaVd/XX47XV90MVmwijF4TWy/0fIWWiON9ufWf5FJBGOahT+toHvAtj/8mHJQjHWZk+FCQi3CcCBXA4WWltW+iAnvPLNUmmKaG6P2YGUOw6Qvw8Qo+R/MhaePZrc+e3hZZ28HLHctFFY5FlJj+5wHqTgcWLfFEnpL5i5i9OTEY/pfJMXer2WF8MVwu5LtfXyUPEz2m7ykmCFDpaYy76qmHJQZp1K3Gj3yHeuNjwbVuicF8JqrEZ30NIOlfQWT6QkpL5hvMYfdi/t3JY+LclW9aM3ZmX2cjwKMf6Qp3XhYEqEPv8ijJwAM/rmKymAGbeKUWGCY7Ory8vQh/tKbvfrjU+RlxIUgUwmgRdgMkGQIeBlpk0GH1xulERik4q/ZNwhCP5B+JGTVIspnqIZ2ThlcbnIrKtcqtIkd3EUDJblYTlgUERWV8BiibwTOejTMrNmxV3vVIoWuFXJXc2YK9AkZhbI3TigasqdnHOnMgpaY/8HTAGZL84KLQaiaQ8eMbTuHzAVKA0Yx5t84vN0A+pBIki+CLuZiBkjJCewovAvJu2/gpAL54GQ31RGhFHwdhuCNufQC/8+OnQpGRWUOGJnCoPZ8T/MWoFhsNpQSim/r0MZwKpF0LHrJeGUA1z+3KwRe7R2mnPcvn1VysNyinmUbS+eE88pbiKtCe88yHsxZ5PkT3hmXBdYAwkd8ayNz9v+cYmobwrkjEuShrZxJHr2SFlAlZ3XhpdcN4YRGg5kGnkCPP6jG1znF8MoGoN3mzF0dg5H9GMnRGNzYHydWqQz1jNZSAPbSC3q3Avl5Uf4smsZT8YzYOO52LTsiNyCsDyYhy5ApVRP+Hu3ynPrY5eplqZqL0KECvfBHXS6OZinqKTGv5n7gitH25A4C431dl4Xx9niiwSF+2xmT3YDz5+gQ1BoMbM3qhzuHn/G7qOaTuboj5K3yU46uNzv90cFQOeZ88I85uLDBFo2PkyVhRh8qnTb+Sem9pgaxNRBHW1HvWCekY+L+t+N1xaIjhXbg3WI7SQAzjWxBy+Hu0CLD2DXNBueFtcva9BV1stP1xKpiBkVi8GgljG7y2SIJbNyKy8vV3+39Yd1h3Wps+dH8GvZndqVSc9D6Fvus+etz5w8VYaEqpCPq8paZHnMe9HqApWFDMrwWXmcyu5z/yL/TQL+VERA9ENfb7yDM1IfGQfZH8vtCnEnoR+86UBpQhbwREkjm6iFinRfhMKD3Q13q5PEZuZ4Ak9i1y5PmqEqPCZVxAw9suT7y14fFRJFI7I/GOOZOay739liZyyMCF3/oXz56FxtOVVwXB+4EkpaBBc4rgwcJC6/SFXWKSOZIpTDgjOCBfX0l/r6cQQ==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: auth
