---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: flux-system
spec:
  encryptedData:
    .env: AgBj7g/ZmIm9wrdhn54us04ngM5NrAcIyqr7+ReqeQ/EpVO72j1h//dJ2y40hsHegnNEQJq3vXXUnoU8J5xw1LLdYNsG+Yoju88KflbENFAdetZDEb30Jwc09+dk1TCajAf/ZFpVh6s/v8xz+bNWlcomeXazuiPzjaVWAtH1DGiMna7m758JYnuIOnojWCYZnGJQHpcf7M/l+Ss/pnQhmtiGAXsOkN+I7U1I/ZOzzRfy9c5mPTeiDs6dDYazgjD/Lq8RSu9GJ5ZKFQncPWwKERy2zlf+bcEhcZOWh9i+smbQ1dBacJSKnKj7wkg+Y6JYGhJvdoIT0B+iSbUqU8a2QJs1SjqxpOmbv/eGKmY2K3F7RhHppinRjWzy5D1ad2ezpOJZ2vWHItpbz/R9qNxfC1FXxELOCNYNxwiu31v36v3wCX4zavHXIW/GbxTo68DSk9YiEibLqLkLkW/WVUpGy2mCfmQTszkHKUx3/eyYFP08U8uY/8eDrho8ppa0zWbalouu8JZJec1Xc6uCd4jlNtMK0foNTXczJg9tcmun+p16M1JVa54yftsTkQsjcjLofVyopnoLR/Q7639VRgyBurb/6vgrenJSoG1JC6owkHhbBGWVn82G5XWA2f29ZRGuDNcJNlEXBRTqSipKgy2pwwHYRarsx1tueon1J+86D7yTg2q/12p+tIOAixzBprPkoVMpRd5HOCxmmHSE9aOK2nyl4ql2Iw+e7cIBXv+Gr0JRufq0UPitsu0jcqbr+o8iX9BuNYc1xAt33NnskVpwC891uT81aNZiheHTocS37x3ADVSqjm791jFPfPEtTpyTRnyucyH8SHYQAdnFJSK4
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: flux-system
    type: Opaque
