---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgC5McPvv6xvfrx5pRTsn38MqzkQOIxae5PYBPJmSuc1EJK3eP+7c3HY4VTAFkMDYjJD/NiarA/BpzZd/I9sxD7b08OojsjbHG3uhvyz+hDHoxrBYTC9tfPMyVf01LA6YtDZM4bVEbL6eAxgmoAEtOEV1531sZAo8BcdwLvgE4E0BVlVp9lSI5AZ5Zn+noiJ37G99KQLZyk2C+6fD5NBy57oNYC3lOLmQkmeBVHufGsfaLMGd1bc6qJ90fbxjqHklXzA2fm9rLROJ4CYCe5MfotpQ8hQFjCYXwZ1n1yRd8GElJF7S4snuzojcPWZwKP6ayM9PlI7HT8V3jlTa4RcXvsHcW8fQeZ/EUZnx41rd5ggittemWCb93W0/hpyiK7gg4TSD0ViuiANCRmyPIAHtj55qDsyAPII4+9HujeF5zkn+osF4gD2eSV3xvs0hQM42IKbxNmhG3ljw2/qj8KGd7KAwl06bv78sFGqx5iK4uxMcvieI6n6KAuVB5AZIG5PD0Y9l92LRp4hpjhScpVE6OKA7RwpWjXWrBCQ9nx4s/4xJ9HcTZSVgduHMkVoNj7iRtrSNtDNbvyqd3crTDIig8y0L4SnuQNla5yhP/uiF3OYPf9XnLKYmC1Wy0+cr8cr4nFMRIPwtjxHCTt9asu9YBuDeULtR8s8yMJrwEQa61fqYq4wMIkN0t1ff5kJJJQowPbmvLqeo1AaE44cctr9fOhjBmaiO2BcRAknW8rj3Z0pGjBxDTQRmlTyv9JV9wEdjDgQc8dfAuU0oLLsBQAGMEtXohBBl5+VdjGS5u26uiYQlzQ+CCD2om/dv2FiOkDnje/+mRyd7EH7dI9mq4CrBbBcdWiCuBM8g4zKea9xciTxsAHzPP69+KDJ3rOJEd5aaepcck+hV19LqZvwCosqd/2I4DW5yiJcR4ZBssDGrinSgIlx/H489aPJ+0mElg+i6OJPJBVra9EK4Q5sOjD61uEjMZxrbpTuuuTHHLGEZfhX+uhYybGRBhpePPzC1AXzA+OCffL14Pq0JHmaAOA3xeDU2YGDGQPegoBScAUJ7njgaHCXGsobbjwQKJzJ7mFqaxbtWRCU++QZczV0zAkbf91Y6eNgreZJwBdLDH0/ijW5l10KeeO77AaJJ8dP6/FAFyLjVs0ZGCGWstRot075781ka9Wh/xMwhoJtJFGO9Ok6T/enH+GsNQPUrhTnxTLuF2iYzvzRqFcGQIO/ll4h7q2Qj8X/qvcc1HCBCsA33OzxaK5kV8w4xWAiBtqmLo9tn7KAGjI09YBZXChgl+TupAQKumZgIZebTA8LDTghiAdS+zbt5RIM/if1FbeDpWW+hqpz7sHt9cE7fW0DAkPp/pWcsBNw6SVC9VHKgX08DnBOYOE01v35SxuMdxl/lBYbhGci7uIWDlm7+e6TzckpUgUThhj+nGeEhknLHbFLREh2pDmLFLdn20Is6XTpXn/Pigxk1Sd4L9vPDA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: flux-system
