---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secrets
  namespace: flux-system
spec:
  encryptedData:
    .env: AgBSILdkqyh6oj60qFFKyGnVtE8M8siz5RQFBky76owXatBy/Y5Y44Slh1P4HElHcUSuXLWagE3Fq6IQjLmXdUGl9eZd/xt0loQzXAR9abrGuHQY3qNMl5mUp422yWf/V8X1U2iHX8Z+lxAINtOoBUIfHe9LbrD8hHalW9swXOOOmGYaxrE58N2pfvY3RY/YXRXEbrCENiGzF+UsQKbmVrkyaJKonGkeS8xjmDRIH9FD/aAROy8l2oLRkPuYtaTtgHLlHSjlvlsLht/3uaFt9e/Rihf7O7oH6e7V8Hav8VXWdQdOoH0T41KCDQKvy8UQOdMEl53wRnrUVWCOgCViygVORy5yenPFfuNkRfpLVcL7WoaOxrA44Tgy9Fi5xHcsvaYFICTeJxInyv8xaZCs2O/78A9Qb4Rp5Pr336IMYtySwkdMAAvwKmfCjWKTskkYvdGcgko942xaQFz3OYk4YPsPTj/UTjUQNzNlYLyhCs5Sjw3KRyloP8w7QQC11gOFkI8Yi0gLh545krJDCBSgZp8+D9Nx1caO7Md+3cKYADmq4q3MNSJ1x7t4qBEimykcZ+1IhSv+HVxzP8jJULXkWyatd9PPAvqSO/M5kpw08VGgDo+nzn++xOV9EIFcyAJ4KQR9GMExo6+iWChU99dURbynNcXEM/T5kTFSwlEu/JiUXJnWKwml3iFdQvIyd4c/BR9CN/btnzJ9XkFwmNZEt1712wxQFZpE11TXfwSCF5j8e8TVvwoSwWfIk95l52CaJg9J+YnMAVYtewr17n2s6MvrfYqN2oK3YK4M3/vqGFlueLpLQdSsCo5+Hrq/sOSTfDXuiZbXnUHFnQVmX1mjOuWKCKBROQYbxX7OYiZ4sqRoR/LfoKh2g7c+7had5sYnTDzkVOCp5IIA87hF/V2ALLpIkNoBsJVNsIKn04LaX69s8nR0/058dnMSXATNTW8cZiKHSI+AMMpCv8gHOZa/4SS0YCpO4+smkIuFbEUfiEuapD4X++mf/25uxyFRJUCGEM/34Q8yWbRRor+6Mzncp56UBSeoO9bc9diUAuTF79MM+iDWqZQ=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secrets
      namespace: flux-system
    type: Opaque
