apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wl-dns-nix-builder
  namespace: flux-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-egress-nix-builder
  namespace: flux-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: wl-dns
  namespace: flux-system
spec:
  interval: 24h
  storeReadablePlan: human
  approvePlan: auto
  path: ./iac/wl/dns
  sourceRef:
    kind: GitRepository
    name: flux-system
  fileMappings:
    - location: "home"
      path: ".ssh/id_ed25519"
      secretRef:
        name: nixos-builder-key
        key: id_ed25519
    - location: "workspace"
      path: "builder-key"
      secretRef:
        name: nixos-builder-key
        key: id_ed25519
  runnerPodTemplate:
    spec:
      image: ghcr.io/angellusmortis/tf-controller-runner:v0.15.1-nix-17
      initContainers:
        - name: init-perms
          image: alpine:3
          command:
          - chown
          - 65532:65532
          - /nix
          volumeMounts:
          - name: nix
            mountPath: /nix
      volumes:
        - name: nix
          persistentVolumeClaim:
            claimName: wl-dns-nix-builder
      volumeMounts:
        - name: nix
          mountPath: /nix
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: ca-egress-1
  namespace: flux-system
spec:
  interval: 24h
  storeReadablePlan: human
  approvePlan: auto
  path: ./iac/ca/egress
  sourceRef:
    kind: GitRepository
    name: flux-system
  fileMappings:
    - location: "home"
      path: ".ssh/id_ed25519"
      secretRef:
        name: nixos-builder-key
        key: id_ed25519
    - location: "workspace"
      path: "builder-key"
      secretRef:
        name: nixos-builder-key
        key: id_ed25519
  runnerPodTemplate:
    spec:
      image: ghcr.io/angellusmortis/tf-controller-runner:v0.15.1-nix-17
      initContainers:
        - name: init-perms
          image: alpine:3
          command:
          - chown
          - 65532:65532
          - /nix
          volumeMounts:
          - name: nix
            mountPath: /nix
      volumes:
        - name: nix
          persistentVolumeClaim:
            claimName: ca-egress-nix-builder
      volumeMounts:
        - name: nix
          mountPath: /nix
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 15m
  storeReadablePlan: human
  approvePlan: auto
  path: ./iac/authentik
  sourceRef:
    kind: GitRepository
    name: flux-system
  writeOutputsToSecret:
    name: tf-authentik-output
  fileMappings:
    - location: "workspace"
      path: ".env"
      secretRef:
        name: authentik-secrets
        key: .env
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: cloudflare
  namespace: flux-system
spec:
  interval: 15m
  storeReadablePlan: human
  approvePlan: auto
  path: ./iac/cloudflare
  sourceRef:
    kind: GitRepository
    name: flux-system
  writeOutputsToSecret:
    name: tf-cloudflare-output
  fileMappings:
    - location: "workspace"
      path: ".env"
      secretRef:
        name: cloudflare-secrets
        key: .env
  varsFrom:
    - kind: Secret
      name: tf-authentik-output
      varsKeys:
        - cloudflare_oidc_client_id
        - cloudflare_oidc_client_secret
