apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wl-dns-nix-builder
  namespace: flux-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dc-backup-nix-builder
  namespace: flux-system
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: wl-dns
  namespace: flux-system
spec:
  interval: 24h
  approvePlan: auto
  path: ./iac/wl/dns
  sourceRef:
    kind: GitRepository
    name: flux-system
  fileMappings:
    - location: "home"
      path: ".ssh/id_ed25519"
      secretRef:
        name: nixos-builder-key
        key: id_ed25519
    - location: "workspace"
      path: "builder-key"
      secretRef:
        name: nixos-builder-key
        key: id_ed25519
  runnerPodTemplate:
    spec:
      image: ghcr.io/angellusmortis/tf-controller-runner:v0.15.1-nix-12
      initContainers:
        - name: init-perms
          image: alpine:3
          command:
          - chown
          - 65532:65532
          - /nix
          volumeMounts:
          - name: nix
            mountPath: /nix
      volumes:
        - name: nix
          persistentVolumeClaim:
            claimName: wl-dns-nix-builder
      volumeMounts:
        - name: nix
          mountPath: /nix
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: dc-backup
  namespace: flux-system
spec:
  interval: 24h
  approvePlan: auto
  path: ./iac/dc/backup
  sourceRef:
    kind: GitRepository
    name: flux-system
  fileMappings:
    - location: "home"
      path: ".ssh/id_ed25519"
      secretRef:
        name: nixos-builder-key
        key: id_ed25519
    - location: "workspace"
      path: "builder-key"
      secretRef:
        name: nixos-builder-key
        key: id_ed25519
  runnerPodTemplate:
    spec:
      image: ghcr.io/angellusmortis/tf-controller-runner:v0.15.1-nix-12
      initContainers:
        - name: init-perms
          image: alpine:3
          command:
          - chown
          - 65532:65532
          - /nix
          volumeMounts:
          - name: nix
            mountPath: /nix
      volumes:
        - name: nix
          persistentVolumeClaim:
            claimName: dc-backup-nix-builder
      volumeMounts:
        - name: nix
          mountPath: /nix
