---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nixos-builder-key
  namespace: flux-system
spec:
  encryptedData:
    id_ed25519: AgAcmohLPwA/y4bg5wMy6IHabXYJGjGM4tij16G+PLc43Zp/bp8Rh6lsjGyFW59ayr8jXBegBx94VRg7aBwRT/77tkFQQ8mOtcIKbpaHEiC3ABuuBy/srMfsZsI6FzZqCj6yYiMG+ppOqqISHAc6Tny0niSLAA/zEzq/4QEp47Rrdzm/ZvJMg95knO2pJmYKKXVrngKae/u9ulTZHeYeemq3SrNaHLskWjY+7guARABIk41hQyILtJsbza6aVWjqJP66b1rftFSCnmrhYgrnD32NoFwi8UCfzBiRUvXVuShwr/7C6Izr6lYrtxsPOJ+Gt3DLSuIZcZxF/jXB1aeJSxHFCMqR+AB+l0g3k+xkOrN2f69kQCf6+NeYrFYhxD6cozrjk/Hr1kzk5czQPkL8hylue5XSUuC1diHqnm3CXsPToJxcAmd48/AHyos5fzsm9hxRDAkVfkL+lfMc7GKk0YBfBnzo9y4v3zpdOcHzUXqPccZcEcg8iL7se3VfMKsRr3b8/kgTC5pxdLfLL2Az+CvCHwRqKDJtMTXMSbKm+EqdVI8AznVDqLPMygUSRGgOV7zgjEiHxf+Py4D9FiG34u0aQDiaDmVxtYZuTDNnncvLJryCVr3XeBkxQF63YsS+ira4INxV8ase0PLuCIQieTNmYCY0oi7coysb90aNrDvyP/ztStAZMZzq8T89IjmOYnwmRNUjvjUxjhxbMboYc6N7jMnrlBVEzZcSNgL/UxgaiKFm8h2//ax5j9LTWv1TOj9TG/7XBs8IIJBzZ/H3njhlZSXwEyYFkv0e/VEEaGcJBROoCBzYpR/ycC5wDcYPxxrjuth1VskwniIuX2hVtNHt5Xf4N23Pz1cK+5bH3Nma9/wjLTV3AVhqneUVUxGUC94QNVdTRQRdlPgWC8CUgROrv2a6PtYSVfyTmOuwq3/i4iziOIpDZl4BXjOhhdorUGJsRxmBkauGeOjUtPo8rjHzMK+WxNS/5wUK5VIfbrY0+P6mBpIIPR9gpBWSo1ritDZYOYEPlUx9fT/0oBQ7CzAvqyoTEROZh6QCdpXN6v0b15LHN1syF841RfKrttsn4uAAiZgB0tbIb6pI4gEqrig3IrI6gBmWSLpivsr1bPFQU8D9rD3Kh/GlNAD5rdII7TZG1N2IkEbKgOiIhALVil7Vndf6bk+2Nx3GqU42cLVKzule2S3mkv7KQJFofFFfqz/tUWJ28xOshGn0/IzzWzewfdqTZ8PxpBMEao8=
  template:
    metadata:
      creationTimestamp: null
      name: nixos-builder-key
      namespace: flux-system
    type: Opaque
