# kubectl apply -f manifests/debug.yml
# kubectl delete -f manifests/debug.yml

apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - name: debug
    image: ghcr.io/angellusmortis/ark-server:v0.2.2
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - infinity
    volumeMounts:
      - mountPath: /srv/ark/server
        name: server
  volumes:
    - name: server
      persistentVolumeClaim:
        claimName: ark-server-b
