---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: deluge-secrets
  namespace: media
spec:
  encryptedData:
    DELUGE_MONITOR_API_KEY: AgB6pgopQMlXoXSVJq83Pun65y5HgXRQw+9N5ZE6oJRd55FX2pSLM2MCjyrUzqx5ZCSoyJDXvkh44q3tpnthjkW9eKNNFfcdcv60CTXBHG9kdFzkbVVOvbaqdIovNH6snvowIUPujvdY5kC0QjWwHnncddkNe92BtB1Tn9Dn5nxTnBQlTGFxV7zB9QCDZ1kvnzezOMS0p2if5FvWlQk0pV216OWAq2th9j6Cm0uf9pc9lzk6WsEYmq9raprsE4U+MpU3yiXf92Ehql/KvK6z7ZtJFgO43B6SB60NIb2SLKcuf5yYaGn7TTPvu2aHnpRPhMSMnt78S6lFkvINGbXWDYvVscL8KytACG8TAS80m2VDNmacdcyKGlmFWN2PtSNxoa5l0ck71YKtc3sIFzEtkmeSYItEbhEylgl8D+Fba6bBcQW975WCtPX2Kc23v8Cp8e0pJS4XCeYjZj4gy06eRLvV9efMGKyU5xjGfZ7pljdqtYBvNDCdBz3OCyJzGZkgMpq7L2kj/FotTMJf3nVqIBWewZ/M8x0ONgkrUj0Sk1nW58kNv8xXgwyYf2+AVbByKOnC/VV/UE5iop2DiRMVu9JvZ1Et9NNxcOXBq+d1l6l8zrwf+eq9VxL2tjZiRbDxcVsEVRmvXz96OybserrhM/8u5rYgsdS07ivOmosGYu54xDhrvMSf4gPk9JQiDOayO9yBJQUXFW9Vvnz7qfDanUb7+K0A3VsDZyCt+KG2K2jA0IhbXA==
    DELUGE_SYNC_PASSWORD: AgCyLTD+geREB7nkJG31L0BYn2qPdPjxmKpsQoWnhNil2vRZqXtSlJp7elzayy7ABZ9yD9mW4ynFHD2wF/i30uhFVLdtdHjtN5x3QS3Wu/2zqqLlFDJkM39oxJyXZYiGKQE99TsJUGQKWjTuIgZo+EVn5RsQTkGZGHgN7miYjOviYXmpLTAuI4Np8Dz+djXEnNWJYpaRCXYDIuXP609xVvkL/wRsHquPd5vMQ2z8TjGI+v29fEDiJ59Yl9oew5s41haDMBg/c3dWZornuPHi6wrJn49HMCVYbP9SjZKlLUIByIscnotSX0F1xVjtzcQh2vnKj4c1BSzY5U7SOhI/oKUp+NsX1Ek/3UZBYSvHxOSWUcfJ8BHKANmmXj2iQOSKwTjGGccf9l86f4U1q5jD3ln7ulQBHIn7svx9AMgffDTKsbR5+8T4ppLzXzN1OleWcs9hyDPOSo8laTDgZnGd30Jv590yS29uIw+pknlFEenXnb9jhhnQuSWGB7sFSgPyTFI2kvg/SAD/xSOmNqX95v5+dSZTjh8H6YE0Wzpe95/JoKT3r4/ucZGEg60mK/KaN/Nve7Hjaz5jgJYDBMXUYuPksJm9l1IYHkowoIwW9dS4gvgcBEWEoxkjSywD2cq/Ows5a3+23eeGF4E0O+PkeS77H/YCGEQmUV1vh8hyP01HC2t3/14ivVbuPbrm4sT+NMrS17l9HZ7VdA==
  template:
    metadata:
      creationTimestamp: null
      name: deluge-secrets
      namespace: media
    type: Opaque
