apiVersion: v1
kind: ConfigMap
metadata:
  name: deluge-sync-config
  namespace: media
data:
  DELUGE_SYNC_RULES: '[{"host": "aither.cc","priority": 10,"min_time": "P5D","keep_size": 8392},{"host": "avistaz.to","priority": 10,"min_time": "P3D","min_formula": "({min!r}+(timedelta(hours=2)*{size!r})) * {buffer}"},{"host": "blutopia.cc","priority": 10,"min_time": "P10D","keep_size": 10440},{"host": "exoticaz.to","priority": 10,"min_time": "P3D","min_formula": "({min!r}+(timedelta(hours=2)*{size!r})) * {buffer}"},{"host": "flacsfor.me","priority": 10,"min_time": "P7D"},{"host": "myanonamouse.net","priority": 10,"min_time": "P3D","keep_count": 500,"seed_limit": 125,"under_limit_request": {"url": "http://autobrr:7474/api/filters/4/enabled","method": "PUT","headers": {"X-API-Token": "143572390d9ab8424f90e797e274b1a6"},"data": "{\"enabled\":true}"},"over_limit_request": {"url": "http://autobrr:7474/api/filters/4/enabled","method": "PUT","headers": {"X-API-Token": "143572390d9ab8424f90e797e274b1a6"},"data": "{\"enabled\":false}"}},{"host": "opsfet.ch","priority": 10,"min_time": "P7D"},{"host": "seedpool.org","priority": 10,"min_time": "P10D","keep_size": 1200},{"host": "torrentleech.org","priority": 10,"min_time": "P10D","keep_count": 100}]'
  DELUGE_SYNC_LABEL_REMAP: "dns-verify.top=permaseed,opsfet.ch=permaseed,pixelcove.me=permaseed"
  DELUGE_SYNC_LABELS: seeding
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deluge-sync
  namespace: media
  app.kubernetes.io/component: deluge-sync
  app.kubernetes.io/instance: deluge-vpn
  app.kubernetes.io/name: deluge-sync
  app.kubernetes.io/part-of: deluge-vpn
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      metadata:
        labels:
          app.kubernetes.io/component: deluge-sync
          app.kubernetes.io/instance: deluge-vpn
          app.kubernetes.io/name: deluge-sync
          app.kubernetes.io/part-of: deluge-vpn
      template:
        spec:
          metadata:
            labels:
              app.kubernetes.io/component: deluge-sync
              app.kubernetes.io/instance: deluge-vpn
              app.kubernetes.io/name: deluge-sync
              app.kubernetes.io/part-of: deluge-vpn
          containers:
          - name: cleanup
            image: ghcr.io/angellusmortis/deluge-sync:v1.8.1
            imagePullPolicy: IfNotPresent
            command: ["bash"]
            args:
            - "-c"
            - "[[ -z \"${DELUGE_SYNC_RULES}\" ]] && ( echo \"No rules defined\" && exit 1) || ( echo \"$DELUGE_SYNC_RULES\" && echo 'Running sync on seeding...' && deluge-sync sync -l seeding && echo 'Running sync on permaseed...' && deluge-sync sync -l uploaded -l permaseed --no-remove --no-relabel )"
            securityContext:
              runAsUser: 1000
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              seccompProfile:
                type: "RuntimeDefault"
              capabilities:
                drop: ["ALL"]
            envFrom:
              - configMapRef:
                  name: deluge-sync-config
              - secretRef:
                  name: deluge-secrets
            env:
              - name: DELUGE_SYNC_URL
                value: http://deluge-web:8112
              - name: DELUGE_SYNC_PATH_MAP
                value: "aither.cc=/downloads/p/seed/ath,avistaz.to=/downloads/p/seed/az,blutopia.cc=/downloads/p/seed/blu,dns-verify.top=/downloads/p/seed/lsh,exoticaz.to=/downloads/p/seed/ez,flacsfor.me=/downloads/p/seed/red,torrentleech.org=/downloads/p/seed/tl,rptscene.xyz=/downloads/p/seed/rpt,metal-tracker.com=/downloads/p/seed/mt,myanonamouse.net=/downloads/p/seed/mam,opsfet.ch=/downloads/p/seed/ops,pixelcove.me=/downloads/p/seed/pxc,seedpool.org=/downloads/p/seed/sp"
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: deluge-dc-sync
  namespace: media
  app.kubernetes.io/component: deluge-sync
  app.kubernetes.io/instance: deluge-vpn
  app.kubernetes.io/name: deluge-dc-sync
  app.kubernetes.io/part-of: deluge-vpn
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      metadata:
      labels:
        app.kubernetes.io/component: deluge-sync
        app.kubernetes.io/instance: deluge-vpn
        app.kubernetes.io/name: deluge-dc-sync
        app.kubernetes.io/part-of: deluge-vpn
      template:
        spec:
          metadata:
            labels:
              app.kubernetes.io/component: deluge-sync
              app.kubernetes.io/instance: deluge-vpn
              app.kubernetes.io/name: deluge-dc-sync
              app.kubernetes.io/part-of: deluge-vpn
          containers:
          - name: cleanup
            image: ghcr.io/angellusmortis/deluge-sync:v1.8.1
            imagePullPolicy: IfNotPresent
            command: ["bash"]
            args:
            - "-c"
            - "[[ -z \"${DELUGE_SYNC_RULES}\" ]] && ( echo \"No rules defined\" && exit 1) || ( echo \"$DELUGE_SYNC_RULES\" && echo 'Running sync on seeding...' && deluge-sync sync -l seeding && echo 'Running sync on permaseed...' && deluge-sync sync -l uploaded -l permaseed --no-remove --no-relabel )"
            securityContext:
              runAsUser: 1000
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              seccompProfile:
                type: "RuntimeDefault"
              capabilities:
                drop: ["ALL"]
            envFrom:
              - configMapRef:
                  name: deluge-sync-config
              - secretRef:
                  name: deluge-secrets
            env:
              - name: DELUGE_SYNC_URL
                value: http://192.168.52.50:8112
              - name: DELUGE_SYNC_PATH_MAP
                value: "aither.cc=/opt/download/p/seed/ath,avistaz.to=/opt/download/p/seed/az,blutopia.cc=/opt/download/p/seed/blu,dns-verify.top=/opt/download/p/seed/lsh,exoticaz.to=/opt/download/p/seed/ez,flacsfor.me=/opt/download/p/seed/red,torrentleech.org=/opt/download/p/seed/tl,rptscene.xyz=/opt/download/p/seed/rpt,metal-tracker.com=/opt/download/p/seed/mt,myanonamouse.net=/opt/download/p/seed/mam,opsfet.ch=/opt/download/p/seed/ops,pixelcove.me=/opt/download/p/seed/pxc,seedpool.org=/opt/download/p/seed/sp"
          restartPolicy: Never
