apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: ingress
spec:
  interval: 12h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-cert-manager
  namespace: ingress
spec:
  releaseName: cert-manager
  targetNamespace: ingress
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.*"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    crds:
      enabled: true
    prometheus:
      servicemonitor:
        enabled: true
        labels:
          release: prometheus
