apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-downloads
  namespace: media
spec:
  storageClassName: smb-downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-media
  namespace: media
spec:
  storageClassName: smb-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
