---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smbcreds
  namespace: media
spec:
  encryptedData:
    password: AgBpyfsCvYpvh65Inpicov91gAdJHzUWmnnX//OFlNmtWMl1Dt9zjLIJB4K72wbqX+TbNeYR/wA8Vx4QJBjuAKUf2mmr5nZttNlY+nTdgnA4f8uIjmqOdYizjOSGRpjpH/VB4ekVKlqM5MLSfjYb9NkGxl9EjZ8PK6oUlfleX3Mx4dykB4KdZY6AOPaC7C6ORAeoFArYrg1zgFqnQSYXqvTU0LwwvFYj7Nn5DIKG/A05Zp2GYuNACuqJX2Ov+0fAaynnDoDYZNpXWGzwqA15ol3LOs0vo0oAXIH+/ocn7sdYsCFGRwdi0yFE/wZeamB/MOEHBaL7vWs/jnNfUe5s3r7J2LE0KR0yg9muJqR5Q3JSjFHNdPpBEnT3QcD9LDqubOtGNOyXeH3eKyD998Lf2wJJI6AN8Uc5N/6GFxfS6r+M6+WUKnXMV2Sex16MGjt2jz4b6lemoTOAiudC142QwpaJeiyhzkA+rFj6w/ODIWUyw6cGfdBdbxyoTXpH4XsXfyZ/h+tYfwr6b4ZQVKOvfJseaZEU+g7DwZETMy0y010E7IeONuPa4vFJ824DrStfBi5JztEwzm257GPUx9bYmZ3kDJnfk5PEK4dmvJdnz9Cm7iYxTUJKgupkg8GszstDKN+H3+ZMIs6kzBQyqRb6IpPtrvVDMrueQ01naS7s9TW7a3X99lZl1DExNggLzErTDzdTivilFE230shYLD8boIUDwnjfbVGOruCzaFj3VKO6pA==
    username: AgCJk/bWvo1agQnS4uAQl9CQj7dMExp7SvtRVyw/K65xItRH5eyqjxq5iC1AngseTZE5Qi8b1imjWzVsPa2Z45bY3M2iwAavNBAROux64jpvbh+2bODkiwcOZ7Fgs2H/BjDgPh0eNojVlWwoWEmMm52zLgCuIuBTo/9tafVu0hXtGhf8rRymkr64L9fx38msHcriPYeMr9iPTiG4Jg3VV1/8JS4VEp616zrhe8SDO5CYwQmjiY6PPBgY46HTyqXKCiz3l1FTxxJIaiscG/eocwiW60JIBojCKJnXF+REitrMXF82aA54a8RBI6LEq5tjLZ20wifLIQRGwCJvk+w1HBTzU1HRy6wAJ/Q2f7JChVHNGOi+P7MppZ/GmDAQ69iePwkq7ReLR/Y55CdE04Ely9fZvm5qPFRZNQxFXKixMUoieBjaHkPLbVgCbkut9vZkOeddgJB70TYgubR6eZZFfjfO8KWgTHUsKajlbOPBzI4gQmD32fgrPF6oWXQ/NFmlIqVJaOXBffJZXrWNti55QnSxe0kbWfYZ7CfQ2u+ojdmVVYgz9PEl4HlmWZTsATzheFRV9PIwI9U99qVd1ZAdQ8rfkE4zwyePDOYqBg72FD6wvbXgEVD7+JdOkYySGywzrtG1ZByttj58j5mdMWFUP2muEAyZkVWJT7US4NDY6pNXaXJ3VU0hZWZR/8jkvFlTUAxvunq8FyNH
  template:
    metadata:
      creationTimestamp: null
      name: smbcreds
      namespace: media
