apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sync-backup
  namespace: media
spec:
  sourcePVC: nas-backup
  syncthing:
    serviceType: LoadBalancer
    configStorageClassName: longhorn
    moverSecurityContext:
      runAsUser: 1000
    # List of peers that this ReplicationSource should connect to.
    peers:
      # The Syncthing ID of the peer.
    - ID: GVONGZX-6FVQPEY-4QWTVLK-TXNJUHA-5UGA625-UBC7HZQ-P5BG2XJ-EHJ4XQ3
      # The address of the peer - this will be used as a data connection.
      address: tcp://192.168.52.50:22000
      # Whether or not the peer should introduce this ReplicationSource to other peers.
      introducer: false
