apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bridge-mautrix-signal
  namespace: chat
spec:
  interval: 12h
  url: oci://ghcr.io/cyclikal94/matrix-helm-charts/mautrix-signal
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-apps-matrix-bridge-signal
  namespace: chat
spec:
  releaseName: bridge-signal
  targetNamespace: chat
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: bridge-mautrix-signal
  values:
    homeserver:
      address: http://matrix-synapse-synapse.chat.svc.cluster.local:8008
      domain: matrix.chat.mort.is
    config:
      baseExtra: |
        bridge:
          permissions:
            "*": relay
            "mort.is": user
            "@angellus:mort.is": admin
