apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bridge-mautrix-signal
  namespace: chat
spec:
  interval: 12h
  url: oci://ghcr.io/cyclikal94/matrix-helm-charts/mautrix-signal
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-apps-matrix-bridge-signal
  namespace: chat
spec:
  releaseName: bridge-signal
  targetNamespace: chat
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: bridge-mautrix-signal
  values:
    homeserver:
      address: http://matrix-synapse-synapse.chat.svc.cluster.local:8008
      domain: mort.is
    config:
      baseExtra: |
        bridge:
          permissions:
            "*": relay
            "mort.is": user
            "@angellus:mort.is": admin
        backfill:
          enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bridge-mautrix-slack
  namespace: chat
spec:
  interval: 12h
  url: oci://ghcr.io/cyclikal94/matrix-helm-charts/mautrix-slack
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-apps-matrix-bridge-slack
  namespace: chat
spec:
  releaseName: bridge-slack
  targetNamespace: chat
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: bridge-mautrix-slack
  values:
    homeserver:
      address: http://matrix-synapse-synapse.chat.svc.cluster.local:8008
      domain: mort.is
    config:
      baseExtra: |
        bridge:
          permissions:
            "*": relay
            "mort.is": user
            "@angellus:mort.is": admin
        backfill:
          enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bridge-mautrix-meta
  namespace: chat
spec:
  interval: 12h
  url: oci://ghcr.io/cyclikal94/matrix-helm-charts/mautrix-meta
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-apps-matrix-bridge-meta
  namespace: chat
spec:
  releaseName: bridge-meta
  targetNamespace: chat
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: bridge-mautrix-meta
  values:
    homeserver:
      address: http://matrix-synapse-synapse.chat.svc.cluster.local:8008
      domain: mort.is
    config:
      baseExtra: |
        bridge:
          permissions:
            "*": relay
            "mort.is": user
            "@angellus:mort.is": admin
        backfill:
          enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bridge-mautrix-linkedin
  namespace: chat
spec:
  interval: 12h
  url: oci://ghcr.io/cyclikal94/matrix-helm-charts/mautrix-linkedin
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-apps-matrix-bridge-linkedin
  namespace: chat
spec:
  releaseName: bridge-linkedin
  targetNamespace: chat
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: bridge-mautrix-linkedin
  values:
    homeserver:
      address: http://matrix-synapse-synapse.chat.svc.cluster.local:8008
      domain: mort.is
    config:
      baseExtra: |
        bridge:
          permissions:
            "*": relay
            "mort.is": user
            "@angellus:mort.is": admin
        backfill:
          enabled: true
