apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: matrix
  namespace: chat
spec:
  interval: 12h
  url: oci://ghcr.io/element-hq/ess-helm/matrix-stack
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  ref:
    semver: "*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-apps-matrix-synapse
  namespace: chat
spec:
  releaseName: matrix-synapse
  targetNamespace: chat
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: matrix
  values:
    serverName: chat.mort.is
    synapse:
      ingress:
        host: matrix.chat.mort.is
        tlsEnabled: true
        className: "nginx-insecure"
        annotations:
          nginx.ingress.kubernetes.io/upstream-vhost: "matrix.chat.mort.is"
      # logging:
      #   levelOverrides:
      #     synapse.handlers.oidc: DEBUG
      additional:
        0-custom-config:
          config: |
            admin_contact: "mailto:admin@mort.is"
            allow_public_rooms_over_federation: false
            serve_server_wellknown: true
            enable_registration: false
            suppress_key_server_warning: true
            trusted_key_servers:
            - server_name: matrix.org
            password_config:
              enabled: false
        1-custom-config:
          configSecret: oidc-config
          configSecretKey: oidc.yml
    matrixAuthenticationService:
      enabled: false
    matrixRTC:
      replicas: 2
      ingress:
        host: mrtc.chat.mort.is
        tlsEnabled: true
        className: "nginx-insecure"
        annotations:
          nginx.ingress.kubernetes.io/upstream-vhost: "mrtc.chat.mort.is"
      sfu:
        useStunToDiscoverPublicIP: false
    elementWeb:
      replicas: 2
      ingress:
        host: element.chat.mort.is
        tlsEnabled: true
        className: "nginx-insecure"
        annotations:
          nginx.ingress.kubernetes.io/upstream-vhost: "element.chat.mort.is"
    elementAdmin:
      replicas: 2
      ingress:
        host: admin.chat.mort.is
        tlsEnabled: true
        className: "nginx-insecure"
        annotations:
          nginx.ingress.kubernetes.io/upstream-vhost: "admin.chat.mort.is"
