---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-config
  namespace: chat
spec:
  encryptedData:
    oidc.yml: AgA5hZXDi0BbaowDtby9lBQuSvl+nJ5EMmjRWdqA9x1KDc59ggRVAEGYzsyrWvQboBg3QqSgE524KcOTB/Ewv0fKPxsuEYE7g/C5JkeJ1WbTh7zO9WrHDw259UClyznAfcbQjhHyMXP/SUHCtwMi+EYN/5FLFZHXWPWHkbX3acH6hNJMysrn8du1AIY3nNd7Xk4FdAwNBsu4IDVpuAaGpWYejggdxb0IqACg/rQU0zdqch6Q2KZfGmSTxuKkLNIKMclv7fOsRi14/qXxdKYhqr53H01JXF4rqb2QvgczxP7iOIOdYU3Ct/tMlhTJtLGnA7WvPykJPHxg/jOF/pBD05Ci0/dyUpzX4vM9uu0xx/eGUNtWfq0GehNJkuw3AoZCb8h0tecVRpnrOkKyZApABiSsSlWucekmrxk0DwwKrfwmEk0OIIhDnQjlbQLOMnCgzp98aRZVrnoIMsroYmtKu+cAUHMZ/kUzh1ZkujCj5ju0VRvYKK5BkSOIp6ZzGaUaZ4lSa/vlneVqlmsz7XtmKrrdu5NPkIjOdmUyGJ4KHZ8r2agSpwebYHBA8kzvcGU3MsSy6sdrkh/VQn1u278OYujtNz2u6Vy5yGj3yQNKrsEbet6HXlYV5nEE6Fa+B2OQMpvFkfhO/eQSHscfZaVLntKaZRt9aVU3aKRf1mOdxD8eMpquRmQ3V8MO75PilvNR+a37tuMEJMEoHZDWgwI5LSoFLYlsc4wbipSSWeEa0KQc6NM8tF3RPArg08WKimWJVIhkdiRGlEMDQO/eczHijbfe6S+fkY2556rrslQPCcoJA6dBXKtgVFkQR7syJEJY/xquQAyV0ObASz6bEETHl9gqxtWHEga9hzv9BIKsteTVqIfOp3c6hRYWniYIAtj0eMSJw/drap8CKrthgX3oLbwwFOBbkaemAA6K6R5ekJoc3wM0i3A3aLWY4SQh8aKQDBpWAFEUZZ8cqtAbmnweF8RDGWMYfPSJbY9ua+72UfAhBi2RfKNVUP3C9i7wlW5lolv3pRp4bGyiyMskxm2OWuU8bBl1uUO1NkImTknYSXcsTm14FYhcOkxpgl02CYFnTfa4cm9Jh5HXFNGPeLQrMaDjX9s++0IcfNlTHAJ8oR4N9hkzq7Hm1t/MTxiddA8Jys3VxxCyOTY7rlPbCttpiYBK/DyVDo9TZ6IZCUd2oBpY76T5e9/+ObVLi/O7uDzkPs+mvSfPwERh39rBzQzp4k7+2yzKZuoSOTiABH+bI5qN880r9u0cnjkKcy22IM75flduyQ==
  template:
    metadata:
      name: oidc-config
      namespace: chat
    type: Opaque
