---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-config
  namespace: chat
spec:
  encryptedData:
    oidc.yml: AgCmhFAGqSPivDYd4knGiSiPLLnMDGGh6MJbFS06CuSAyBoi5kx0vE3g/cD8l+23p2t5rnJEW/Jq2Kk97i5l4MtGSeoG7jm9vXWnkjkuZQi8qewhfGccv52Hwgd+ikReva9rri7UIde4WctGQlM1tAMyBQQFhnAQa1pgWmEb7qPmLYRxGinZra0CDHVzobWmP7V1Kvww/0oLzU6MIU+pv0lf/D5MA2Tvi9ZGwnnIx3F+31ZZMacwRBmiH5j1OR0p5HE6PIRgpHhM6xV+FqzV2NsxA+b+5MhzHp3BZICSuFtE07P9UVwJApvMlUjOoW5kSq6t2AC7GOZ29VkpJ5JGx5Dnkl8Mmzn4iSAWJmqeSYlGTiBUDSATqWoIPOmxwxdyxqycZdsYd1YJee+lR3QMcNPsfcwTtkGzxFO1oMgPQ4JZaZydZTFoLvLTnWsU9Swncad+afH48YsIAcj1/sHVAiF2PuUi3W5QhDRfr3IzyDwY3nSBVnPrG1UeBXdUnYNvuPADLM3Br0F7/K4WctpLYMEyaOexJyAIXAGw0RYyvIp6DM62UArcG/8WKDV+O2VtnhgqV57hNG//dtamWIIO8BQ2eqd+FFJjLAXPCwfd3uJs6OcpuNuPIoVA/GucmYDCYjk5hfZsNUQorHnTsh4HCqhh+5jTIqGia8D3207tNIJ4DYshXhNwZ6VnSyYPyl94lzfNIF2J4CnzIsb3bL/GqMLxcttS+yLwfbP7ESOjlrX67wSlOJ+SpN35WxVpXoHkmFOX5ggmOx2NMn+IFSAh3E6VoV00IBfh7FFbiox4LSOBOEMIh+nF0jpcyjahxqO2+8cXsIwEm7/P0jMuP9l4UCagUjKV4+zY/oY6f6M2ji9Bdmu8DnUFNdCovt9uwMcRfMm/Ne3OgBaxo3RPiiDmsjDBCgllnecDxn8wIBWcapKOPe/a3PZ1JpLl0FDRQINSyiM4+gHJbuu9hXx72rDbw/v3r8/ytMU/MEW8OhO9Fm/IuwZrJmLTdPqjhg4sGkbQH1r/cw2dkYQHHMuhSsH+pZvu2DqEMwbKnfsaF/N/zIMbNzMA4sktKwPV/jrrLrcQ4M04C7N2O2MVM5wgK6x9KcB8MBLCkoJAdeXtAmFaVjlnpZT5V10qkdbQOMCH3CWZv0D+UiMBqpky2IBRQMaQaN+32wxrh4CaXWC8wBXT+cEhjc3daWBNGHl3pSzPyZEJvqL2042C8BZsExJVzHc1Tpkfgxo=
  template:
    metadata:
      name: oidc-config
      namespace: chat
    type: Opaque
