apiVersion: v1
kind: Secret
metadata:
  name: oidc-config
  namespace: chat
type: Opaque
stringData:
  oidc.yml: |
    oidc_providers:
    - idp_id: authentik
      idp_name: authentik
      discover: true
      issuer: "https://auth.chat.mort.is/application/o/matrix/"
      client_id: "kgDtzZzXxNghnaecdLMzrMWWRRSP5oukzy8qOMmz"
      client_secret: "Iajn8XpTEKy9dDQ1S4RrOiB7Dmh1NbYCXLFMqWTMLQh8R1gvpmyL4N4q6TAPWTomp2vFc18HviVjejw4tzkonw7qAWtjybhobPWeVtpxUBgft4CH32nn8jQrFQsUgjLb"
      scopes:
      - "openid"
      - "profile"
      - "email"
      user_mapping_provider:
        config:
          localpart_template: "{{ user.preferred_username }}"
          display_name_template: "{{ user.name|capitalize }}"
    jwt_config:
      enabled: true
      secret: "Iajn8XpTEKy9dDQ1S4RrOiB7Dmh1NbYCXLFMqWTMLQh8R1gvpmyL4N4q6TAPWTomp2vFc18HviVjejw4tzkonw7qAWtjybhobPWeVtpxUBgft4CH32nn8jQrFQsUgjLb"
      algorithm: "RS256"
