apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: disks-longhorn
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/03-disks/01-longhorn
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: disks-openebs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/03-disks/02-openebs
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: disks-openebs-post
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/03-disks/02-openebs/post
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: disks-csi-driver-smb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/03-disks/03-smb-driver
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
