---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backup-secret
  namespace: longhorn-system
spec:
  encryptedData:
    # SECRET: -> smb -> config.yml
    CIFS_PASSWORD: AgBx3WN0iYAmPTWcHdj5Ucd8KXIcKEN+3Wli54appEdPSDGMXRwXAY+Valt6LTTxrm8cLRcN/rLJI40/V5C7kNcXA0/lvfopdYk7e8ODJ+HniEGaOv+1Vz5D+g5yinhch1eSNnLqSjdsIpEAGwuhDTC4xhqcpIFXe2bzq0hdIWynXw6JN0xNQ1bO214EmCnUozy04CxmwZTZNXoA/oAG6cKHblqdrwYlLgCPZFNhHEtyG1Lnke2r+/J/CuLmBLOCSqB5WV3Lk3LxqPSNm7Slx6WbjeT+MvN8v6IaN9HKUILY+X+e7xMw3k8hJcI/9TJt29IKlbWvR108jbBRO80BEVD4sI+vI62+PYbAzHwy9YnMpBLAd+9Y0H2LPurSbeP2q+qDXEQefphVPtA0P1Nw1Kc2QziQn+Zo3blcKXMa/ks8wXw/zZ/53cRvzb+uwY+CaLu8SfixMO7U7OJAhMDj7Ovp9mDXx8lSo+nXmD0QUwEtISiSGpII5tnkzdI2Zxwlah6guMJcCyzLQ9VkyKyxPBPr5WIiNN5UuePXfli/+akg3WhNHwQl5XVkHeoxxFlcy2sMC6kWrEaHUnthJ/1+w6Js3fdjAV/04SctSjigGpqrRGHcIdB86rxcm4TyL365pdefzN/GbJr8DRUe/i06Z5VpFHb7AhC7AmJp7uC6cxwXfbYKj2A92UT9pgI0gES/ToM24ORQQoMM9Awbi8yuYwHJBdwKBIb7GPqUdJbMbiEH6Q==
    CIFS_USERNAME: AgCe77uFuO/IQCa/Uaq5lM15j5R/0zfzfNH036ZFFyGFvdzvqENKKFkEzzzGUno85IFVCE0OPmWYXwiSH6pZ2/OFx0zi0MZIzRDfH9tfobFirf6XDCjufqPqXF3aJjUHZm+XQLJsJMFccuAXC3zwiNvqgdipbZ+RUVD5EuDIOpRB99TqRVzLboNFTJTAB6CpggI6oREjlD/kaip8xDOkn21k1dAV2vMTKuWaKr1vWhILVA4+afekiEa+hfBIGyVBNUy62iDsQSIeJsbZKHvZaOJXRYOBzfAUkp4vOEf0LOLJpKkH+BZwNqlLyfGGyaROfgmQhaemApFTxbNCdbKXxl6LiqJVbszBVaobI2iLtUd8t4tAh36nzAAnU1kq25+/nHen1TGfO7rRbQUkZbSfaDKNHnVLEHVviSGnkYtheN28VLoSLlLwIhLRSeXCRv2H0ar3Wf/Gr7+lekCse8Bw95j/IA6iFKOLffCZynVZjiuiamp1ScO6YHtl/mBZ/7x/P+XXhGmhr3KnTYggJRbQ4RmcvZveA4KUv9WypNKv8NsjN+wItgj+JfktU7LF2M55TBJSwHTJXi4IxCU2U87wl7ciG/kzP6zbTUltINzw94xeKBjNj/Cj1+mt3bMJzxNxVTW4D5jJPEdGGHUf2Bf1ue5wZfTWcfdWlLtt/kpLdxJlARAwmnrZL7wcer9DvG2Ub+l3F/UiYEva
  template:
    metadata:
      creationTimestamp: null
      name: backup-secret
      namespace: longhorn-system
    type: Opaque
