apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 12h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: disks-longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  targetNamespace: longhorn-system
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: longhorn
      version: "v1.7.*"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: longhorn
  values:
    defaultSettings:
      backupTarget: cifs://smb-samba.media.svc.cluster.local/backup/k8s/longhorn
      backupTargetCredentialSecret: backup-secret
    ingress:
      enabled: true
      ingressClassName: nginx-secure
      host: longhorn.wl.mort.is
      tls: true
      tlsSecret: ~
      annotations:
        nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.auth.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: |-
            https://auth.wl.mort.is/outpost.goauthentik.io/start?rd=$scheme%3A%2F%2F$host$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
    metrics:
      enabled: true
      additionalLabels:
        release: prometheus
