apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-create-chronicles
  namespace: games
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
