apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-cobblemon-plus
  namespace: games
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
