apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-endventure
  namespace: games
spec:
  storageClassName: longhorn-games
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-backup
  namespace: games
spec:
  storageClassName: smb-backup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
