#!/bin/bash

DISABLED_NODES="fake"

if [[ -z "$1" ]]; then
    kubectl get pod -o=wide -A | grep -v Running | grep -v Completed | grep -v -E "$DISABLED_NODES"
else
    kubectl get pod -o=wide -A | grep -v Running | grep -v Completed | grep $1 | grep -v -E "$DISABLED_NODES"
fi
