#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

baseDir="$(readlink -f "$(dirname "$0")/../")"
command="switch"
extra_args=""
build=""

function parse_args() {
    POSITIONAL_ARGS=()

    while [[ $# -gt 0 ]]; do
    case $1 in
        --dry)
        command="build"
        shift # past argument
        ;;
        --build-host)
        extra_args="$extra_args --build-host $2"
        shift # past argument
        shift # past value
        ;;
        --target-host)
        extra_args="$extra_args --target-host $2"
        shift # past argument
        shift # past value
        ;;
        -*|--*)
        echo "Unknown option $1"
        exit 1
        ;;
        *)
        POSITIONAL_ARGS+=("$1") # save positional arg
        shift # past argument
        ;;
    esac
    done

    set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

    build="$1"
}


parse_args "$@"
echo "Build ($build) command: $command $extra_args"
NIXOS_CONFIG="$baseDir/iac/nix/$build/configuration.nix" nixos-rebuild $command --upgrade-all --sudo $extra_args
