#!/bin/bash

type="${1:-all}"

#talosctl works in parallel. Do each node in sequence
if [[ $type == "all" ]] || [[ $type == "control" ]]; then
    talosctl reboot -n cluster-1
fi
if [[ $type == "all" ]] || [[ $type == "nodes" ]]; then
    talosctl reboot -n cluster-3 -n cluster-4
    talosctl reboot -n cluster-5 -n cluster-6
fi
if [[ $type == "all" ]] || [[ $type == "control" ]]; then
    talosctl reboot -n cluster-2
fi
