#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

baseDir="$(dirname "$0")"
certFile="$(realpath "$baseDir/../ss-pub.pem")"
secretPath="$1"
filename="$(basename "$secretPath")"
filename="${filename%.*}"
outputFolder="$(dirname "$secretPath")"


if [[ ! -f "$certFile" ]]; then
    "$baseDir"/update-ss-pub
fi

kubeseal --format=yaml --cert="$certFile" < "$secretPath" > "$outputFolder/$filename-sealed.yml"
rm "$secretPath"
