apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ark-club-ark
  namespace: games
  labels:
    app.kubernetes.io/component: club-ark
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
spec:
  replicas: 1
  serviceName: ark-club-ark
  selector:
    matchLabels:
      app.kubernetes.io/component: club-ark
      app.kubernetes.io/instance: ark
      app.kubernetes.io/name: ark
      app.kubernetes.io/part-of: ark
  template:
    metadata:
      labels:
        app.kubernetes.io/component: club-ark
        app.kubernetes.io/instance: ark
        app.kubernetes.io/name: ark
        app.kubernetes.io/part-of: ark
    spec:
      nodeSelector:
        kubernetes.io/hostname: games-1
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "gamesOnly"
        effect: "PreferNoSchedule"
      containers:
      - name: ark
        image: ghcr.io/angellusmortis/ark-server:v0.6.0
        imagePullPolicy: IfNotPresent
        command: [ "/entrypoint" ]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 7780
          name: ark-club-ark
          protocol: UDP
        - containerPort: 27020
          name: rcon-club-ark
          protocol: TCP
        envFrom:
          - secretRef:
              name: ark-cluster-secrets
        env:
          - name: ARK_SERVER_MAX_PLAYERS
            value: "10"
          - name: ARK_SERVER_CLUSTER_ID
            value: "mortis"
          - name: ARK_SERVER_BATTLEYE
            value: "false"
          - name: ARK_SERVER_WHITELIST
            value: "true"
          - name: ARK_SERVER_RCON_PORT
            value: "27020"
          - name: ARK_SERVER_SESSION_NAME
            value: Mortis - Club Ark
          - name: ARK_SERVER_MAP
            value: "BobsMissions_WP"
          - name: ARK_SERVER_GAME_PORT
            value: "7780"
          - name: ARK_SERVER_AUTO_UPDATE
            value: "false"
          - name: ARK_SERVER_CLUSTER_MODE
            value: "true"
        volumeMounts:
          - mountPath: /srv/ark/server
            name: server
          - mountPath: /srv/ark/data
            name: data
          - mountPath: /srv/ark/server/ark/ShooterGame/Saved
            name: data
            subPath: maps/BobsMissions_WP/saved
          - mountPath: /srv/ark/server/ark/ShooterGame/Binaries/Win64/ShooterGame
            name: data
            subPath: maps/BobsMissions_WP/mods
          - mountPath: /srv/ark/server/ark/ShooterGame/Binaries/Win64/PlayersExclusiveJoinList.txt
            name: data
            subPath: lists/PlayersExclusiveJoinList.txt
          - mountPath: /srv/ark/server/ark/ShooterGame/Binaries/Win64/PlayersJoinNoCheckList.txt
            name: data
            subPath: lists/PlayersJoinNoCheckList.txt
        resources:
          limits:
            cpu: 6000m
            memory: 24Gi
          requests:
            cpu: 3000m
            memory: 10Gi
        readinessProbe:
          exec:
            command: [ sh, -c, arkctl server --host 127.0.0.1 rcon ListPlayers ]
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          exec:
            command: [ sh, -c, test -f "/srv/ark/server/ark/ShooterGame/Saved/.started" ]
          initialDelaySeconds: 5
          # 60 minutes to update
          failureThreshold: 360
          periodSeconds: 10

      volumes:
      - name: server
        persistentVolumeClaim:
          claimName: ark-server-a
      - name: data
        persistentVolumeClaim:
          claimName: ark-data
