apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ark-island
  namespace: games
  labels:
    app.kubernetes.io/component: island
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
spec:
  replicas: 1
  serviceName: ark-island
  selector:
    matchLabels:
      app.kubernetes.io/component: island
      app.kubernetes.io/instance: ark
      app.kubernetes.io/name: ark
      app.kubernetes.io/part-of: ark
  template:
    metadata:
      labels:
        app.kubernetes.io/component: island
        app.kubernetes.io/instance: ark
        app.kubernetes.io/name: ark
        app.kubernetes.io/part-of: ark
    spec:
      nodeSelector:
        kubernetes.io/hostname: games-1
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "gamesOnly"
        effect: "PreferNoSchedule"
      containers:
      - name: ark
        image: ghcr.io/angellusmortis/ark-server:master
        imagePullPolicy: Always
        command: [ "/entrypoint" ]
        securityContext:
          runAsUser: 10000
          runAsGroup: 10000
          fsGroup: 10000
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 7781
          name: ark-island
          protocol: UDP
        - containerPort: 27021
          name: rcon-island
          protocol: TCP
        envFrom:
          - configMapRef:
              name: ark-config
          - secretRef:
              name: ark-secrets
        env:
          - name: ARK_SERVER_SESSION_NAME
            value: "Mortis - The Island"
          - name: ARK_SERVER_MAP
            value: "TheIsland_WP"
          - name: ARK_SERVER_RCON_PORT
            value: "27021"
          - name: ARK_SERVER_GAME_PORT
            value: "7781"
        volumeMounts:
          - mountPath: /srv/ark/server
            name: server
            readOnly: true
          - mountPath: /srv/ark/data
            name: data
          - mountPath: /srv/ark/server/ark/ShooterGame/Saved
            name: data
            subPath: maps/TheIsland_WP/saved
          - mountPath: /srv/ark/server/ark/ShooterGame/Binaries/Win64/ShooterGame
            name: data
            subPath: maps/TheIsland_WP/mods
          - mountPath: /srv/ark/data/clusters
            name: data-old
            subPath: clusters
        resources:
          limits:
            cpu: 6000m
            memory: 24Gi
          requests:
            cpu: 3000m
            memory: 10Gi
        readinessProbe:
          exec:
            command: [ sh, -c, arkctl server --host 127.0.0.1 rcon ListPlayers ]
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        startupProbe:
          exec:
            command: [ sh, -c, test -f "/srv/ark/server/ark/ShooterGame/Saved/.started" ]
          initialDelaySeconds: 5
          # 60 minutes to update
          failureThreshold: 360
          periodSeconds: 10

      volumes:
      - name: server
        persistentVolumeClaim:
          claimName: ark-server-a
      - name: data
        persistentVolumeClaim:
          claimName: ark-data
      - name: data-old
        persistentVolumeClaim:
          claimName: ark-save-data
