apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ark-se
  namespace: games
  labels:
    app.kubernetes.io/component: se
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
spec:
  replicas: 1
  serviceName: ark-se
  selector:
    matchLabels:
      app.kubernetes.io/component: se
      app.kubernetes.io/instance: ark
      app.kubernetes.io/name: ark
      app.kubernetes.io/part-of: ark
  template:
    metadata:
      labels:
        app.kubernetes.io/component: se
        app.kubernetes.io/instance: ark
        app.kubernetes.io/name: ark
        app.kubernetes.io/part-of: ark
    spec:
      nodeSelector:
        kubernetes.io/hostname: games-1
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "gamesOnly"
        effect: "PreferNoSchedule"
      containers:
      - name: ark
        image: ghcr.io/angellusmortis/ark-server:v0.3.3
        imagePullPolicy: IfNotPresent
        command: [ "/entrypoint" ]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 7783
          name: ark-se
          protocol: UDP
        - containerPort: 27023
          name: rcon-se
          protocol: TCP
        envFrom:
          - configMapRef:
              name: ark-config
          - secretRef:
              name: ark-secrets
        env:
          - name: ARK_SERVER_SESSION_NAME
            value: "Mortis - Scorched Earth"
          - name: ARK_SERVER_MAP
            value: "ScorchedEarth_WP"
          - name: ARK_SERVER_RCON_PORT
            value: "27023"
          - name: ARK_SERVER_GAME_PORT
            value: "7783"
        volumeMounts:
          - mountPath: /srv/ark/server
            name: server
            readOnly: true
          - mountPath: /srv/ark/data
            name: data
          - mountPath: /srv/ark/server/ark/ShooterGame/Saved
            name: data
            subPath: maps/ScorchedEarth_WP/saved
          - mountPath: /srv/ark/server/ark/ShooterGame/Binaries/Win64/ShooterGame
            name: data
            subPath: maps/ScorchedEarth_WP/mods
          - mountPath: /srv/ark/server/ark/ShooterGame/Binaries/Win64/PlayersExclusiveJoinList.txt
            name: data
            subPath: lists/PlayersExclusiveJoinList.txt
          - mountPath: /srv/ark/server/ark/ShooterGame/Binaries/Win64/PlayersJoinNoCheckList.txt
            name: data
            subPath: lists/PlayersJoinNoCheckList.txt
          - mountPath: /srv/ark/data/clusters
            name: data-old
            subPath: clusters
          - mountPath: /srv/ark/server/ark/ShooterGame/Saved/Config/WindowsServer/Game.ini
            name: config
            subPath: Game.ini
          - mountPath: /srv/ark/data/GameUserSettings.ini
            name: config
            subPath: GameUserSettings.ini
        resources:
          limits:
            cpu: 6000m
            memory: 24Gi
          requests:
            cpu: 3000m
            memory: 10Gi
        readinessProbe:
          exec:
            command: [ sh, -c, arkctl server --host 127.0.0.1 rcon ListPlayers ]
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          exec:
            command: [ sh, -c, test -f "/srv/ark/server/ark/ShooterGame/Saved/.started" ]
          initialDelaySeconds: 5
          # 60 minutes to update
          failureThreshold: 360
          periodSeconds: 10

      volumes:
      - name: server
        persistentVolumeClaim:
          claimName: ark-server-a
      - name: data
        persistentVolumeClaim:
          claimName: ark-data
      - name: data-old
        persistentVolumeClaim:
          claimName: ark-save-data
      - name: config
        configMap:
          name: ark-global-ark-config
