apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ark-aberration
  namespace: games
  labels:
    app.kubernetes.io/component: aberration
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
spec:
  replicas: 1
  serviceName: ark-aberration
  selector:
    matchLabels:
      app.kubernetes.io/component: aberration
      app.kubernetes.io/instance: ark
      app.kubernetes.io/name: ark
      app.kubernetes.io/part-of: ark
  template:
    metadata:
      labels:
        app.kubernetes.io/component: aberration
        app.kubernetes.io/instance: ark
        app.kubernetes.io/name: ark
        app.kubernetes.io/part-of: ark
    spec:
      nodeSelector:
        kubernetes.io/hostname: games-1
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "gamesOnly"
        effect: "PreferNoSchedule"
      containers:
      - name: ark
        image: sknnr/ark-ascended-server:v1.5.2
        imagePullPolicy: IfNotPresent
        command: [ "/home/steam/ark/entrypoint.sh" ]
        securityContext:
          runAsUser: 10000
          runAsGroup: 10000
          fsGroup: 10000
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 7784
          name: ark-aberration
          protocol: UDP
        - containerPort: 27020
          name: rcon
          protocol: TCP
        envFrom:
          - configMapRef:
              name: ark-config
          - secretRef:
              name: ark-secrets
        env:
          - name: SESSION_NAME
            value: "\"Mortis - Aberration\""
          - name: SERVER_MAP
            value: "Aberration_WP"
          - name: GAME_PORT
            value: "7784"
          - name: AUTO_UPDATE
            value: "false"
        volumeMounts:
          - mountPath: /home/steam
            name: server
          - mountPath: /home/steam/ark/ShooterGame/Binaries/Win64/ShooterGame
            name: data
            subPath: Aberration_WP/mods
          - mountPath: /home/steam/ark/data
            name: data
          - mountPath: /home/steam/ark/ShooterGame/Saved
            name: data
            subPath: Aberration_WP
        resources:
          limits:
            cpu: 6000m
            memory: 24Gi
          requests:
            cpu: 3000m
            memory: 10Gi
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - rcon -a 127.0.0.1:${RCON_PORT} -p ${SERVER_ADMIN_PASSWORD} listplayers
          initialDelaySeconds: 90 # Should be about how long it takes for Full Startup in logs
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 20
          successThreshold: 1
        startupProbe:
          exec:
            command:
              - sh
              - -c
              - test ! -f "${ARK_PATH}/ShooterGame/Saved/SavedArks/${SERVER_MAP}/.pre-setup"
          initialDelaySeconds: 5
          # 60 minutes to update
          failureThreshold: 360
          periodSeconds: 10
      volumes:
      - name: server
        persistentVolumeClaim:
          claimName: ark
      - name: data
        persistentVolumeClaim:
          claimName: ark-save-data
