apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: cloud-storage-db
  namespace: games
spec:
  secretName: cloud-storage-db
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-storage
  namespace: games
  labels:
    app.kubernetes.io/name: cloud-storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: cloud-storage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloud-storage
    spec:
      containers:
      - name: app
        image: arkcloudstorage/api:1.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: ws
          containerPort: 3000
        envFrom:
          - secretRef:
              name: cloud-storage-secrets
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
          limits:
            cpu: "2000m"
            memory: "1000Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-storage
  namespace: games
  labels:
    app.kubernetes.io/name: cloud-storage
spec:
  type: ClusterIP
  ports:
    - name: ws
      port: 3000
      targetPort: ws
      protocol: TCP
  selector:
    app.kubernetes.io/name: cloud-storage
