apiVersion: mort.is/v1beta1
kind: ArkCluster
metadata:
  name: ark
  namespace: games
  labels:
    app.kubernetes.io/name: arkcluster
    app.kubernetes.io/instance: ark
    app.kubernetes.io/component: cluster
spec:
  service:
    loadBalancerIP: 192.168.3.243
  server:
    gracefulShutdown: 10m
    size: 50Gi
    persist: true
    maps: [ "@official" ]
    gamePortStart: 7780
    rconPortStart: 27020
    storageClass: longhorn-games
    resources:
      limits:
        cpu: 6000m
        memory: 24Gi
      requests:
        cpu: 3000m
        memory: 10Gi
  data:
    persist: true
    size: 100Gi
  globalSettings:
    sessionNameFormat: "Mortis - {map_name}"
    maxPlayers: 10
    clusterID: mortis
    battleye: false
    allowedPlatforms: [ ALL ]
    whitelist: true
    opts: [ "ForceAllowCaveFlyers" , "GBUsageToForceRestart=22", "forceuseperfthreads", "ServerUseEventColors" ]
    mods: [ 928548, 1114862, 1121944, 1121958, 947733, 940975, 939688, 953154, 935528, 947033, 928501, 1108923, 1102356, 929785, 1163881, 1123898, 1056780, 1101570, 928708, 930115 ]
    # WC Mods:
    # Club ARK: 1005639

    # Seasonal Mods:
    # Love Ascended: 927084
    # Summer Bash: 927091
    # Fear Ascended: 877752
    # Turkey Trial: 927083
    # Winter Wonderland: 927090

    # Other Mods:
    # Shiny: 928548
    # Trait Upgrader: 1114862
    # Illuminating Trait: 1121944
    # Assorted Traits: 1121958
    # Automated Dino Wipes: 947733
    # Cybers Structures QoL+: 940975
    # Lily's Tweaker: 939688
    # Auto Engrams!: 953154
    # Visual Storage: 935528
    # Awesome Spyglass!: 947033
    # Solo Farm Mod: 928501
    # Neo Ark Ascended: The Reaper: 1108923
    # Better Sir-5rM8: 1102356
    # Crafting Skill Potion: 929785
    # Cloud Storage: 1123898
    # LACC: Lily and Azure's Cluster Chat: 1056780
    # Sparky: 1101570
    # Custom Dino Levels: 928708
    # Grpyhons: 930115

    # Better Horde Mode: 1163881
  runAsUser: 1000
  runAsGroup: 1000
  nodeSelector:
    kubernetes.io/hostname: games-1
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "gamesOnly"
      effect: "PreferNoSchedule"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-map-envs-extinction
  namespace: games
data:
  ARK_SERVER_MODS: 1163881,928548,1114862,1121944,1121958,947733,940975,939688,953154,935528,947033,928501,1108923,1102356,929785,1123898,1056780,1101570,928708,930115
