apiVersion: mort.is/v1beta1
kind: ArkCluster
metadata:
  name: ark
  namespace: games
spec:
  server:
    size: 50Gi
    persist: true
    maps: [ "@official" ]
    gamePortStart: 7780
    rconPortStart: 27020
    maxPlayers: 10
    battleye: false
    allowedPlatforms: [ ALL ]
    whitelist: true
    storageClass: longhorn-games
  data:
    persist: true
    size: 100Gi
  cluster:
    clusterID: mortis
  runAsUser: 1000
  runAsGroup: 1000
  nodeSelector:
    kubernetes.io/hostname: games-1
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "gamesOnly"
      effect: "PreferNoSchedule"
