apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-operator
  namespace: games
  labels:
    app.kubernetes.io/name: ark-operator
    app.kubernetes.io/instance: ark-operator
    app.kubernetes.io/version: v0.8.1
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: ark-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ark-operator
      app.kubernetes.io/instance: ark-operator
      app.kubernetes.io/component: operator
      app.kubernetes.io/part-of: ark-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ark-operator
        app.kubernetes.io/instance: ark-operator
        app.kubernetes.io/version: v0.8.1
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: ark-operator
    spec:
      serviceAccountName: ark-operator
      containers:
      - name: app
        image: ghcr.io/angellusmortis/ark-operator:v0.8.1
        imagePullPolicy: IfNotPresent
        # image: ghcr.io/angellusmortis/ark-operator:master
        # imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
          - name: ARK_CLUSTER_NAMESPACE
            value: games
          - name: ARK_OP_LOG_LEVEL
            value: DEBUG
          - name: ARK_SERVER_IMAGE_VERSION
            value: v0.8.1
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
          limits:
            cpu: "2000m"
            memory: "4000Mi"
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 20
          successThreshold: 1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: games
  name: ark-operator
  labels:
    app.kubernetes.io/name: ark-operator
    app.kubernetes.io/instance: ark-operator
    app.kubernetes.io/version: v0.8.1
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: ark-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ark-operator-games-role-cluster
  labels:
    app.kubernetes.io/name: ark-operator
    app.kubernetes.io/instance: ark-operator
    app.kubernetes.io/version: v0.8.1
    app.kubernetes.io/component: cluster-role
    app.kubernetes.io/part-of: ark-operator
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [mort.is]
    resources: [arkclusters]
    verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ark-operator-games-rolebinding-cluster
  labels:
    app.kubernetes.io/name: ark-operator
    app.kubernetes.io/instance: ark-operator
    app.kubernetes.io/version: v0.8.1
    app.kubernetes.io/component: cluster-role-binding
    app.kubernetes.io/part-of: ark-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ark-operator-games-role-cluster
subjects:
  - kind: ServiceAccount
    name: ark-operator
    namespace: games
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: games
  name: ark-operator-role-namespaced
  labels:
    app.kubernetes.io/name: ark-operator
    app.kubernetes.io/instance: ark-operator
    app.kubernetes.io/version: v0.8.1
    app.kubernetes.io/component: role
    app.kubernetes.io/part-of: ark-operator
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [mort.is]
    resources: [arkclusters]
    verbs: [list, watch, patch]

  # Application: other resources it produces and manipulates.
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [pods, persistentvolumeclaims, configmaps, secrets]
    verbs: ["*"]
  - apiGroups: [mort.is]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: games
  name: ark-operator-rolebinding-namespaced
  labels:
    app.kubernetes.io/name: ark-operator
    app.kubernetes.io/instance: ark-operator
    app.kubernetes.io/version: v0.8.1
    app.kubernetes.io/component: role-binding
    app.kubernetes.io/part-of: ark-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ark-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: ark-operator
---
apiVersion: mort.is/v1beta1
kind: ArkCluster
metadata:
  name: ark
  namespace: games
  labels:
    app.kubernetes.io/name: arkcluster
    app.kubernetes.io/instance: ark
    app.kubernetes.io/version: v0.8.1
    app.kubernetes.io/component: cluster
spec:
  server:
    loadBalancerIP: 192.168.3.243
    gracefulShutdown: 10m
    size: 50Gi
    persist: true
    maps: [ "@official" ]
    gamePortStart: 7780
    rconPortStart: 27020
    storageClass: longhorn-games
    resources:
      limits:
        cpu: 6000m
        memory: 24Gi
      requests:
        cpu: 3000m
        memory: 10Gi
  data:
    persist: true
    size: 100Gi
  globalSettings:
    sessionNameFormat: "Mortis - {map_name}"
    maxPlayers: 10
    clusterID: mortis
    battleye: false
    allowedPlatforms: [ ALL ]
    whitelist: true
    opts: [ "ForceAllowCaveFlyers" , "GBUsageToForceRestart=22", "forceuseperfthreads", "ServerUseEventColors" ]
    mods: [ 928548, 1114862, 1121944, 1121958, 947733, 940975, 939688, 953154, 935528, 947033, 928501, 1108923, 1102356, 929785, 1163881, 1123898, 1056780, 1101570, 928708, 930115 ]
    # WC Mods:
    # Club ARK: 1005639

    # Seasonal Mods:
    # Love Ascended: 927084
    # Summer Bash: 927091
    # Fear Ascended: 877752
    # Turkey Trial: 927083
    # Winter Wonderland: 927090

    # Other Mods:
    # Shiny: 928548
    # Visual Storage: 935528
    # Awesome Spyglass!: 947033
    # Grpyhons: 930115
    # Lily's Tweaker: 939688
    # Auto Engrams!: 953154
    # Automated Dino Wipes: 947733
    # Cybers Structures QoL+: 940975
    # Solo Farm Mod: 928501
    # Trait Upgrader: 1114862
    # Illuminating Trait: 1121944
    # Assorted Traits: 1121958
    # Neo Ark Ascended: The Reaper: 1108923
    # Better Sir-5rM8: 1102356
    # Crafting Skill Potion: 929785
    # Better Horde Mode: 1163881
    # Cloud Storage: 1123898
    # LACC: Lily and Azure's Cluster Chat: 1056780
    # Sparky: 1101570
    # Custom Dino Levels: 928708
  runAsUser: 1000
  runAsGroup: 1000
  nodeSelector:
    kubernetes.io/hostname: games-1
  tolerations:
    - key: "type"
      operator: "Equal"
      value: "gamesOnly"
      effect: "PreferNoSchedule"
