apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-config
  namespace: games
data:
  EXTRA_FLAGS: "-WinLiveMaxPlayers=10 -clusterid=mortis -ClusterDirOverride=/home/steam/ark/data -NoTransferFromFiltering -ForceAllowCaveFlyers -GBUsageToForceRestart=22 -NoBattlEye -forceuseperfthreads -ServerPlatform=ALL -exclusivejoin -MULTIHOME -mods=927090,928548,1114862,1121944,1121958,947733,940975,939688,953154,935528,947033,928501,1108923,930115 -ServerUseEventColors -DynamicColorset=\"ActualBlack,Cyan,DeepPink,Dino Dark Purple,Mint,Lavender,Dino Light Purple,Dino Light Blue,DragonGreen0,Jade,PineGreen,SpruceGreen,DarkMagenta,Glacial,PowderBlue,Teal,DarkViolet,Red,Green,Light Grey,Light Red,Dark Red,Dino Light Red,Dino Light Green,Dino Medium Green,Dino Albino,NearWhite,Yellow\""
  EXTRA_SETTINGS: "?serverPVE=True"
  RCON_PORT: "27020"
# WC Mods:
# Dear Jane: 983782
# Club ARK: 1005639

# Seasonal Mods:
# Love Ascended: 927084
# Summer Bash: 927091
# Fear Ascended: 877752
# Turkey Trial: 927083
# Winter Wonderland: 927090

# Other Mods:
# Shiny: 928548
# Visual Storage: 935528
# Awesome Spyglass!: 947033
# Grpyhons: 930115
# Lily's Tweaker: 939688
# Auto Engrams!: 953154
# Automated Dino Wipes: 947733
# Cybers Structures QoL+: 940975
# Solo Farm Mod: 928501
# Trait Upgrader: 1114862
# Illuminating Trait: 1121944
# Assorted Traits: 1121958
# Neo Ark AScended: The Reaper: 1108923
