resources:
  - pvc.yml
  - wg-secrets-sealed.yml
  - config.yml
  - secrets-sealed.yml
  # Club Ark
  - 00-club-ark-secrets-sealed.yml
  - 00-club-ark.yml
  # The Island
  - 01-island-secrets-sealed.yml
  - 01-island.yml
  # The Center
  - 02-center-secrets-sealed.yml
  - 02-center.yml
  # Scorched Earth
  - 03-se-secrets-sealed.yml
  - 03-se.yml
  # Aberration
  - 04-aberration-secrets-sealed.yml
  # - 04-aberration.yml
