apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lacc-data
  namespace: games
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lacc-api
  namespace: games
  labels:
    app.kubernetes.io/name: lacc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lacc-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lacc-api
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: app
        image: ghcr.io/angellusmortis/lacc-api:v1.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: ws
          containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
          limits:
            cpu: "2000m"
            memory: "1000Mi"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lacc-data
---
apiVersion: v1
kind: Service
metadata:
  name: lacc-api
  namespace: games
  labels:
    app.kubernetes.io/name: lacc-api
spec:
  type: ClusterIP
  ports:
    - name: ws
      port: 8080
      targetPort: ws
      protocol: TCP
  selector:
    app.kubernetes.io/name: lacc-api
