apiVersion: v1
kind: Service
metadata:
  name: ark-island
  namespace: games
  labels:
    app.kubernetes.io/component: island
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
  annotations:
    metallb.universe.tf/allow-shared-ip: "ark-192.168.3.242"
    metallb.universe.tf/loadBalancerIPs: 192.168.3.242
spec:
  selector:
    app.kubernetes.io/component: island
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
  ports:
    - name: ark
      port: 7778
      targetPort: ark
      protocol: UDP
  externalTrafficPolicy: Local
  type: LoadBalancer
