apiVersion: v1
kind: Service
metadata:
  name: ark
  namespace: games
  labels:
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
  annotations:
    metallb.universe.tf/allow-shared-ip: "ark-192.168.3.243"
spec:
  loadBalancerIP: 192.168.3.243
  selector:
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
  ports:
    - name: ark-club-ark
      port: 7780
      targetPort: ark-club-ark
      protocol: UDP
    - name: ark-center
      port: 7782
      targetPort: ark-center
      protocol: UDP
    - name: ark-se
      port: 7783
      targetPort: ark-se
      protocol: UDP
    - name: ark-aberration
      port: 7784
      targetPort: ark-aberration
      protocol: UDP
    - name: ark-extinction
      port: 7785
      targetPort: ark-extinction
      protocol: UDP
  externalTrafficPolicy: Local
  type: LoadBalancer
