apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ark-island
  namespace: games
  labels:
    app.kubernetes.io/component: island
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
spec:
  replicas: 1
  serviceName: ark-island
  selector:
    matchLabels:
      app.kubernetes.io/component: island
      app.kubernetes.io/instance: ark
      app.kubernetes.io/name: ark
      app.kubernetes.io/part-of: ark
  securityContext:
    runAsNonRoot: true
  template:
    metadata:
      labels:
        app.kubernetes.io/component: island
        app.kubernetes.io/instance: ark
        app.kubernetes.io/name: ark
        app.kubernetes.io/part-of: ark
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/hostname: games-1
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "gamesOnly"
        effect: "PreferNoSchedule"
      containers:
      - name: ark
        image: sknnr/ark-ascended-server:v1.5.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7777
          name: ark
          protocol: UDP
        - containerPort: 27020
          name: rcon
          protocol: TCP
        envFrom:
          - secretRef:
              name: ark-secrets
        env:
          - name: SESSION_NAME
            value: "Mortis"
          - name: SERVER_MAP
            value: "TheIsland_WP"
          - name: EXTRA_FLAGS
            value: "-WinLiveMaxPlayers=10 -clusterid=mortis -ClusterDirOverride=/home/steam/ark/cluster-shared -NoTransferFromFiltering -ForceAllowCaveFlyers -GBUsageToForceRestart=22 -NoBattlEye -UseDynamicConfig -forceuseperfthreads -ServerPlatform=ALL"
          - name: EXTRA_SETTINGS
            value: "?serverPVE=True"
          - name: GAME_PORT
            value: "7777"
          - name: RCON_PORT
            value: "27020"
        volumeMounts:
          - mountPath: /home/steam/ark
            name: data
        resources:
          limits:
            cpu: 6000m
            memory: 24Gi
          requests:
            cpu: 4000m
            memory: 10Gi
        livenessProbe:
          tcpSocket:
            port: rcon
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          exec:
            command:
            - rcon
            - -a
            - 127.0.0.1:${RCON_PORT}
            - -p
            - ${SERVER_ADMIN_PASSWORD}
            - listplayers
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          exec:
            command:
              - sh
              - -c
              - test ! -f "${ARK_PATH}/ShooterGame/Saved/test"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ark
