apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ark-island
  namespace: games
  labels:
    app.kubernetes.io/component: island
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
spec:
  replicas: 1
  serviceName: ark-island
  selector:
    matchLabels:
      app.kubernetes.io/component: island
      app.kubernetes.io/instance: ark
      app.kubernetes.io/name: ark
      app.kubernetes.io/part-of: ark
  template:
    metadata:
      labels:
        app.kubernetes.io/component: island
        app.kubernetes.io/instance: ark
        app.kubernetes.io/name: ark
        app.kubernetes.io/part-of: ark
    spec:
      nodeSelector:
        kubernetes.io/hostname: games-1
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "gamesOnly"
        effect: "PreferNoSchedule"
      containers:
      - name: ark
        image: sknnr/ark-ascended-server:v1.5.2
        imagePullPolicy: IfNotPresent
        command: /usr/bin/start_server
        ports:
        - containerPort: 7777
          name: ark
        - containerPort: 27020
          name: rcon
        # envFrom:
        #   - secretRef:
        #       name: minecraft-secrets
        env:
          - name: SESSION_NAME
            value: "Mortis"
          - name: SERVER_MAP
            value: "TheIsland_WP"
          - name: EXTRA_FLAGS
            value: "-WinLiveMaxPlayers=10 -clusterid=mortis -ClusterDirOverride=/home/steam/ark/cluster-shared -NoTransferFromFiltering"
          - name: EXTRA_SETTINGS
            value: "?serverPVE=True"
        volumeMounts:
          - mountPath: /home/steam/ark
            name: data
        resources:
            cpu: 6000m
            memory: 24Gi
          requests:
            cpu: 4000m
            memory: 10Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ark
