apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ark-tunnel
  namespace: games
  labels:
    app.kubernetes.io/component: tunnel
    app.kubernetes.io/instance: ark
    app.kubernetes.io/name: ark
    app.kubernetes.io/part-of: ark
spec:
  replicas: 1
  serviceName: ark-tunnel
  selector:
    matchLabels:
      app.kubernetes.io/component: tunnel
      app.kubernetes.io/instance: ark
      app.kubernetes.io/name: ark
      app.kubernetes.io/part-of: ark
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tunnel
        app.kubernetes.io/instance: ark
        app.kubernetes.io/name: ark
        app.kubernetes.io/part-of: ark
    spec:
      nodeSelector:
        kubernetes.io/hostname: games-1
      tolerations:
      - key: "type"
        operator: "Equal"
        value: "gamesOnly"
        effect: "PreferNoSchedule"
      containers:
      - name: gluetun
        image: ghcr.io/qdm12/gluetun:v3.39.1 # {"$imagepolicy": "flux-system:gluetun-policy"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: gluetun-control
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        livenessProbe:
          tcpSocket:
            port: gluetun-control
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: "/v1/publicip/ip"
            port: gluetun-control
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        envFrom:
        - secretRef:
            name: wg-secrets
        - secretRef:
            name: wg-secrets-ark-club
        env:
        - name: TZ
          value: "America/New_York"
        - name: VPN_SERVICE_PROVIDER
          value: "custom"
        - name: VPN_TYPE
          value: "wireguard"
        - name: WIREGUARD_ADDRESSES
          value: "10.8.0.120/32"
        - name: FIREWALL_DEBUG
          value: "on"
        - name: FIREWALL_INPUT_PORTS
          value: "8000,27020,7780,7781,7782,7783,7784,7785"
        - name: FIREWALL_VPN_INPUT_PORTS
          value: "7780,7781,7782,7783,7784,7785"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "192.168.20.0/23,192.168.3.243/32"
        resources:
          limits:
            cpu: "2000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: gluetun
          mountPath: /gluetun

  volumeClaimTemplates:
  - metadata:
      name: gluetun
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
