apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: syncthing
  namespace: media
spec:
  interval: 12h
  url: oci://tccr.io/truecharts/syncthing
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  ref:
    semver: "20.*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: media-apps-syncthing
  namespace: media
spec:
  releaseName: syncthing
  targetNamespace: media
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: syncthing
  values:
    service:
      listeners:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: "sync-192.168.3.236"
          metallb.universe.tf/loadBalancerIPs: 192.168.3.236
      listeners-udp:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: "sync-192.168.3.236"
          metallb.universe.tf/loadBalancerIPs: 192.168.3.236
      discovery:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: "sync-192.168.3.236"
          metallb.universe.tf/loadBalancerIPs: 192.168.3.236
    persistence:
      config:
        enabled: true
        size: 25Gi
        mountPath: "/var/syncthing"

      syncthing:
        enabled: true
        type: pvc
        existingClaim: nas-nvme-syncthing
        mountPath: /mnt/syncthing
      backup:
        enabled: true
        type: pvc
        existingClaim: nas-backup
        mountPath: /mnt/backup
      media:
        enabled: true
        type: pvc
        existingClaim: nas-media
        mountPath: /mnt/media

    securityContext:
      container:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/upstream-vhost: "sync.wl.mort.is"
          nginx.ingress.kubernetes.io/auth-url: |-
              http://ak-outpost-authentik-embedded-outpost.auth.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
              https://auth.wl.mort.is/outpost.goauthentik.io/start?rd=$scheme%3A%2F%2F$host$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
              proxy_set_header X-Forwarded-Host $http_host;
          nginx.ingress.kubernetes.io/proxy-body-size: 512m
        ingressClassName:  "nginx-secure"
        hosts:
          - host: sync.wl.mort.is
            paths:
                - path: /
                  pathType: Prefix
                  overrideService:
                    name: main
                    port: 8384
        integrations:
          certManager:
            enabled: false
          traefik:
            enabled: false
          homepage:
            enabled: false
