apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-namespace-egress
  namespace: media
spec:
  # Apply to all pods in this namespace
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  # Allow DNS traffic
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: plex
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: samba
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: flaresolverr
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: prowlarr
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: bazarr
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: lidarr
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: radarr
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: sonarr
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: deluge-vpn
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: fileflows
    - podSelector:
        matchLabels:
          cnpg.io/cluster: arr-postgres
    # Allow traffic to internet (but not internal network)
    - ipBlock:
        cidr: '0.0.0.0/0'
        except: ['10.96.0.0/12', '10.244.0.0/16']
