apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-backup
  namespace: media
spec:
  storageClassName: openebs-ssd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-nvme-download
  namespace: media
spec:
  storageClassName: openebs-nvme
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-nvme-syncthing
  namespace: media
spec:
  storageClassName: openebs-nvme
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-media
  namespace: media
spec:
  storageClassName: openebs-ssd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-lh-public
  namespace: media
spec:
  storageClassName: openebs-ssd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
