apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-public
  namespace: games
spec:
  storageClassName: smb-public
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
