apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 12h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: system-metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  targetNamespace: metallb-system
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      version: "0.14.*"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: metallb
  values:
    prometheus:
      serviceAccount: "prometheus-kube-prometheus-prometheus"
      namespace: "monitor"
      podMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
