---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-secret-key
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_SECRET_KEY: AgC9sTG4YRYSrsc9UY6zQr5qCF6RsqqYYVOSFuPF4/nUkBb2KgPNhJQRi+XH2M7khVlibigf4xTRRQLBnD+z+PlYtp+k9ay8CPzLuyGRehaQf6LB6LeB0JISCvg7i9Q7xAGrjLQSkgLfzgSoWTos8j/gcsWpkuH9foK5Kq16oRRe12jVvBlXQhaxEa5MtGEVzUic8Nkl4jSvlnO6ytZgp+RympUPtZX9QVjif64/e7oIyAcc47dsXM+f3uMuGt1gBZxjWylVpsbP611nwZgwN9TdelcqpOjJRrkRz/dmQ9rz8o54SV6fiZZwJusRX/rMneSfwgDlnmCcCCzHh3qqM3lQmSr51+9AVomK94hxWvxRThYQdxIcpFa4QorN7ozAZMyxc7yQ9soV7DYGTD5bhLwPhsqWlQBX9y8bi5p3WxkEmccMQVxGj4hu6wk6ED75WLC408kAnA5hoP/qSUsCv1STGFl5Y1iF+2B4MqGogWchuwTGz5/IQmHVZHXrx/Jow9ed2zRVjx1KJth1A05k5YZrMwmKZzMSfceIOy5CX4LpLbCcUcQu8jrJ190tzvKN/d7GVJ/9cefguDzantTXkHiJUklOtpilUxTdSg7D/LjSfguEx7TuYZKQ9H3iPaVjG3y0a0qLsCY6qDfOaZQm1ZKp8PERltnHOGb++MwL64/J2zk6p2Thvg4kREPwrrs8SjyKMUb3x67B64HHf7qHJp5buiHcZ1ZzVscmOOzqjX2JcQ==
  template:
    metadata:
      creationTimestamp: null
      name: paperless-secret-key
      namespace: paperless
