---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: auth
spec:
  encryptedData:
    values.yaml: AgCoAsFzkiacMbJ+NfIbdSb3/2kxU+biwJt/wKF0eulmOXmZex72LvSWZI6Vf9H8LGMhJk88Vtzl26e99haHpfXZxksTPVfHxggbaZROVHLYWTqlXfcV6n4fpQnB3utbGvbovuzkOZBWWFHAyrUsmAK1HVUhGBQJy7DaHUeqppfj36OLGCegoDIcp1YY5EfbQfkSf3ACxsePttNsUvq7Xa9rI5FbcVaf6kEl7o7xYCr6J+11vkmCqogq4Y/6fKXmQude1e1qNEpOIghfkC63m4+B2myzXWDJL+BE3dF40L4mFfdyV5Z3iKHr4KSdezG3RpuTdxTmI5sRH+I3+rRoAVCMVuhM4PeBW6MEkL9prfHF6PNFQV1XbIGCzl9Mx/n3Ph8Mo4gIRHSPcVKyJbTzGk8En0Xd9QeHHcPHl+9pti+U0yxbR8O8Y2q9hC5oHhBwUsNT09JMN+1zsPYZ+Ge1F/xVEEGS7xT69in5lqf2F0FY3JFgoWiV3OGKrlpizDt7fsoM++usVeHiY0g/0vH5hkmIsWwppxbtohAHLTdKMf1pNtbi9IbMQ9zMcDde02SWVpI7bLX+mtmYs7aN/jY3M1N4gMdlozAkWL+fT9FcVcu9ZAP0dVryZyK+7qStx18VCzWrdDPziYGHdSzzRxWTb6ey1vVnEtU7vl3oVaouk1ZAjSXedhBsPw2jcvw7JqzpZBdJGNZ0J3vTSIkRj9vZ+WpBonQkqfl3+64ga+N5dlH0+0mtuB4Aa32Nd7fHX802x+Z+2bgHjHjs34SexuAQEmP7tQ52c/E1a+kA1ZpsXQODUJW+KHzeTQEHQU0yApzTStSC9CKO74uDhQPNYNyBSizxZuRVnDns9KqAIyD8wbAbItwVo/BbcSsjf74U1va+k6sFjvR+FgC7Uck+kwmnUrOIn7PKnuVRj16iN2Ewi/0pZ/fixi+DZC4YpeI9yTvif+5DgWJ0SFk0F2dwvja6X/yguNTe/XLcfBUauWmTjgeuDz5gpHsa+RtCoyKWyOdjLPH+8+NukGAZhyAidDGlIfyZFEnpItf79IPg4ZovJ07WhVXkvfHbPS8b4fLRDVnZO4k36CZhcEfomysFMQeZ16HfcJDodExXngIBi1orLT6nYowJkdP84pzQymDm6CF6VzKBkD6UDx2MX+goE8cNWgFssvGrsm5aTGg1WsOrsvTiGfenuEVvyGnd0yV0NVYq8Q7/Qs1qHjaAtg9wJhMxqexja8Uv5HXaiifNdkVrpa7maKeDydBGu8+EcR2XKSVUNrarY9a2acwHfaCZYg88PvrhyBbd0QXcloUmg7gWydLS4i0y4eEHkDHAdg1DjxgMo0cLfEuy0dbVO3kBGYnsg7+Nxgsoe+Ej+/eUw7Kol1hVa9h4Vj6HZ/LidtNuOCMBo4ESWJXK31Jp/9aos6hYMOIW7UNARUzS8s+ImbYnHfi2Tv+vuFoUWGD+sSbUvJIJluJuFxmGGmfNNA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: auth
