apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-auth-wl-mort-is
  namespace: auth
spec:
  secretName: cert-auth-wl-mort-is
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: auth.wl.mort.is
  dnsNames:
  - auth.wl.mort.is
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-auth-chat-mort-is
  namespace: auth
spec:
  secretName: cert-auth-chat-mort-is
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: auth.chat.mort.is
  dnsNames:
  - auth.chat.mort.is
