apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoip-db
  namespace: auth
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
