apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dragonwilds
  namespace: games
  labels:
    app.kubernetes.io/component: dragonwilds
    app.kubernetes.io/instance: dragonwilds
    app.kubernetes.io/name: dragonwilds
    app.kubernetes.io/part-of: dragonwilds
spec:
  replicas: 1
  serviceName: dragonwilds
  selector:
    matchLabels:
      app.kubernetes.io/component: dragonwilds
      app.kubernetes.io/instance: dragonwilds
      app.kubernetes.io/name: dragonwilds
      app.kubernetes.io/part-of: dragonwilds
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dragonwilds
        app.kubernetes.io/instance: dragonwilds
        app.kubernetes.io/name: dragonwilds
        app.kubernetes.io/part-of: dragonwilds
    spec:
      containers:
      - name: server
        image: indifferentbroccoli/runescape-dragonwilds-server-docker:v1.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: game
          containerPort: 7777
          protocol: UDP
        envFrom:
          - secretRef:
              name: dragonwilds-secrets
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: UPDATE_ON_START
            value: "true"
          - name: SERVER_NAME
            value: Mortis
          - name: DEFAULT_WORLD_NAME
            value: Stuff
        volumeMounts:
          - mountPath: /home/steam/server-files
            name: data
        resources:
          limits:
            cpu: 4000m
            memory: 16Gi
          requests:
            cpu: 1000m
            memory: 8Gi
        securityContext:
          allowPrivilegeEscalation: true
          runAsNonRoot: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: dragonwilds
