apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: postgres-operator
spec:
  interval: 12h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: core-apps-cloudnative-pg
  namespace: postgres-operator
spec:
  releaseName: operator
  targetNamespace: postgres-operator
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.22.*"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: cnpg
  values:
    data:
      WATCH_NAMESPACE: auth,paperless,boundlexx
    monitoring:
      podMonitorAdditionalLabels:
        release: prometheus
