apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: unpoller
  namespace: monitor
spec:
  interval: 12h
  url: oci://tccr.io/truecharts/unpoller
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  ref:
    semver: "12.*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-apps-unpoller
  namespace: monitor
spec:
  releaseName: unpoller
  targetNamespace: monitor
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: unpoller
  values:
    metrics:
      main:
        labels:
          release: prometheus
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                UP_UNIFI_DEFAULT_URL: "https://network-control.wl.mort.is"
                UP_UNIFI_DEFAULT_USER:
                  secretKeyRef:
                    expandObjectName: false
                    name: unifi-unpoller
                    key: username
                UP_UNIFI_DEFAULT_PASS:
                  secretKeyRef:
                    expandObjectName: false
                    name: unifi-unpoller
                    key: password
                UP_PROMETHEUS_DISABLE: "false"
                UP_UNIFI_DEFAULT_SAVE_DPI: "true"
