---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: auth
spec:
  encryptedData:
    values.yaml: AgCv3Wkf5/ONoHJ42U7xq57Lw0WE5vzSEbkZtDhh2LkjCx85iGDPilPNqmnFFRi2oW6uQbl5G1EfZsOVmSMe3P1Rf5maGydDMeuSfVmZk7cZXKNegg3ur/0Qt8kt3yR9YEAvEZR2dqV/qc+AlUFjl+qYKxgDBgr30NcRGlA1wN1oGPlQ7UotO8Znmr+8nBWO0iKqvPxSrtBVOmLbrMQlUYT3s7VCnsfi6uziv02O1EkSKyTLicJMvk+hL84La2gqBWYXMTwk3727Dha/nrzdRBi4SMkcqtFz1sUJdHXcWnMcWozWdo/bxClBDdqLgaIWITa2MhcuUtuYl/wI8+qiOBkPeOla9EwHpusUqeHDh09WLBgceV5ntWR+AO03n74h+ZF37D8PjBieCrv0X5Da1erBDG5pH+vm21HsqmX7jx1aZhy++Up7Y1KW5NL/X9tvtDOd2oiUJBdcdSNNzCjSBg72qHKBmExieSDl/j6V1rXK7tLEHTGdyx+fbhVVkayXJpxqd5Ekfz/bQbALVbMr5ax9+ws0Eey7B0Q6fFC+DWpnNcyu/G+315QkrHtiJcRp756VoVfTFOpce8fXC6y1VCgAaKGaN3TdwgEuNbWtJXx/Q0qbN48sXWIs3XKBVLKQYVsoltizwWN9/idXu4mNdse05MZiStpvMTLQXuUnZa9hMd9hpme/gyYIhLfMKPhm+yJo4HTYRpDL01foranlM3z98gk6iD4zuDLTNxNkOl77ml9Pz9puD+AnrmRkt9APlXjcV+CfWferpama6docAwfFYmMj6i9HCAX543oUe2VF2oJWZx5bWVUziGb/WMXb1VuIkAzh7j5rNQkkjq8a4XDolOk6yKaibQOcLvub93mpdEHJX9aRbEhmrQ9LduMTcUBrSzZZnZPQVnTUF+x1CfqPYfR+qge/eT/L6e3tNbmYPovAI50mleBVTvQUAQDOdKA+3dySSlRU95vCzyaazD+xumonkoW5BUThqYojr0PJbA6yZiykPzPCcn1v2KHFu5E65jTNmE5RpqdmwJc2RHoRLQmVLs5aXRF/qntQ+eejc52i6QHXXUboR2hwp0ssl65BT13N7Z0GdINmzbfqpaUMMkl2isZ56q1tMCNYAeu1wJZjlMeqGdqvuhmF4Uk4Z4G0Mo14tEC6+CbxXA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: auth
    type: Opaque
