---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: romm-secrets
  namespace: media
spec:
  encryptedData:
    values.yaml: AgA+z89QUMnHvgZFg3+BBr65Y7SC5gpoYx+wDxu4rEjoQRs7N6tq8naNuOYA3JD2oFM8cRphPWOmJICSa5uA+AzEt4vIhDdt92a85WKlkLZJIOlDsxj3Bwtysh5Ioxi4ktwdG1Miv12Ga+SzMYnUdfr4Yo8ynNlFWRDpgtclC+V3zoFGv8jLeMdgtCTG8hmnaueHX6F6rzqCuzd0jpf7eiq/Fu4UTauLqfSbp95GXUT26sDOhg44sdYNsLyDsALDu+QoBgNrd4OYePg4DY6LwdTRs57vNkGSldSPp5inBaBxgeeg9AUnyHHhPehuUP06KtcuthFHa0xvQRKoJwfFa+fx+qZK8Xc5wrYMQTjtgxfsc+anHlzMC8XSC4aJifv+dIDjp+ShAlMLU8iVqaEIcflkr5/T+7reztY+NDVVS8y45PHvR/3TtZImV2beZvbmwwJt/AJuTjAWP9FUZD+HY+nqmGeO7wV6NrQssVHluiWMvPYa+qj4PeEurFJc5Q6KPOnYopIoINfrTPqe8Y97RVIpTQ1QPHO6M4UmSSmjP6v0oh02543QW3oT6HMPzl7t44LnRmywn4lRcN3PqbXwZfu57RJmgJUMaUWg5ywlDYqcSRSEEavAh9ek5bBa72DBKZLzN5fPc41x8XpRUktA0SA4mgRLBO4N61a14TCNmPQ0RKXJ/aKeoxXEE6uAVcV+uiA4N3rwktCA1wos1ICPNDhPlexF+qw5fITuXummVFLtcv7KUeMQm3Wd3/sJTQxAEiFFbbbUjGjQh+RWb/WeQlsFakwwsJyWz3HFqC0H6i+fpgKtXyMzRux2D1ZIp2wcPYcEeIoLB9kdkXR5KqzW+sr3A7k3WpMwSubwCpNvtOkc7tA7emF0w8cci4X4aC3kGSQJydHN+XFyVzvuDTszRtol87BCg+n7PYhkqY8fpmz05Ctr+CqQzBllVnQi3AEe6VYvPe0lury417brzUd6TBpc6ICWBG/2FEGrrShMvYpRMVac1FYoqr3+gyNXqj8vE+X4u2Mm1sqGLWHTgamXqapgENGu9AuGXPQeqmEy8qvg+/OWswLc8NyPFq27Pn1uBDC4LWxGlXmuvfYMKjfX1UvS1CDb1DSZHqO749YFLArcv2h6K/5M2ZzQ4A9cimugJzLJv49Hsqc6bOLvcDaRzhkla0+KPMWXJcfp
  template:
    metadata:
      creationTimestamp: null
      name: romm-secrets
      namespace: media
    type: Opaque
