---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: romm-secrets
  namespace: media
spec:
  encryptedData:
    values.yaml: AgCfRzXEpF1stsEve7BsROplWQogiJTTGKRkFtU45soaTvoqdm1GzrYPer+hyAOg7TjGW9tOa1md9+5qMFCbKEykcjLwn0ZTFhIA4TBVDoJk4K2wdPKiarJ5nmXbcTv7uw/sUzXWVScQS9JrMHrUIsg5t0gFRVf4G5EmsY3kwAR3OwJ9LljCptYGRbkhvBPDB0ymGahTJoPfSkOYRZWHaaqfOYcKXHL7NaAbT2hyAHwPpyjWq/n7I0UxwJo3pTLxUYsQWaUtB+0ueWk6wvrr3klHCBNAwcWN3jVFaJZjD/PXE37My3UMtDSo6eIx2VC3ak9ys7bDKOiyenNRsA+TjjCkZ+3MDccx0qEnjI+3p6Wmtt4AOOmgUENc/KU/BiYJ1XRWrggjTxz08VSXswFg+hGuUzbksMcO2pSZ5iEDPnOsyMk/yxdB4OzQuFlidIOstsKsLYW0q2Sxd/iWO2bS1EqHJrlZzBsorHMUYxKX9CPoXqLFHnk9cvEqjFG0yenYq5nZ3Gznt5jkG68A9Zj9z1ZmU0gHNS/k4ss1ucM8tr86aFYmUEkKl0tk9lq/lyvNw/Yu9U48jGd7c8nJjHaY49xjacDOZw/WWM/r/aIt3h6MWCJ7aaICG1g12waUosFOZwbHIalcdbSRrZ6fAb2qfaHldeDaVa+87KzHzGDU0sK/XCY2NVrfkdNZF04ZWRJd5yQO1ffI2Pqp8vOkHEW0HNT1usSzGtPnyJ+18EJYAox4e9FVN5lDPaj0h1Gn+aBq8cf5M4H8yGqcOHGVn5BBiGYBkUCgd0aPTE+sZJbcRn/sa5CRvnf+3f1Aggrph3Atx1gTc4IhshOo7a+NSSMIdYInic9uVsdgSFo8rVp3p/ayKCWo+WYPtpKPk8EvcalFqWFlk5I632Bz5/r5aFZ+MpPzXNt7V83HjMtVat9fdLeD+sjC7thzK4oRjYnpsUYLR4kFICSknNdodmrFeOQ00TsKJp5UzdUJb4vC3fWswSA/08YdmuJscTiz0BVXqqZ+ns7O8VaCSibb3/ZyR8wr2O3PxGcMwl6Q5SKMikALjKtDxe0c1j0z67ev5wrvydjEFDik+i3xy3aHMS5Xankk/dXzViJMM0eyvtsKug2u4+0LvLvbH/D1toioUhZ7sp37tFvrc6wtBFqboVhJEQ==
  template:
    metadata:
      creationTimestamp: null
      name: romm-secrets
      namespace: media
    type: Opaque
