apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs-system
spec:
  interval: 12h
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: disks-openebs
  namespace: openebs-system
spec:
  releaseName: openebs
  targetNamespace: openebs-system
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: openebs
      version: "4.1.*"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: openebs
  values:
    zfs-localpv:
      zfsNode:
        encrKeysDir: /var/openebs/keys
    mayastor:
      enabled: false
    engines:
      local:
        lvm:
          enabled: false
      replicated:
        mayastor:
          enabled: false
